// Code generated by ent, DO NOT EDIT.

package nodelogtarget

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodelogtarget type in the database.
	Label = "node_log_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldIsSyslog holds the string denoting the is_syslog field in the database.
	FieldIsSyslog = "is_syslog"
	// FieldIsOff holds the string denoting the is_off field in the database.
	FieldIsOff = "is_off"
	// FieldHasVariable holds the string denoting the has_variable field in the database.
	FieldHasVariable = "has_variable"
	// FieldSkipReason holds the string denoting the skip_reason field in the database.
	FieldSkipReason = "skip_reason"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldInode holds the string denoting the inode field in the database.
	FieldInode = "inode"
	// FieldStatErr holds the string denoting the stat_err field in the database.
	FieldStatErr = "stat_err"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// Table holds the table name of the nodelogtarget in the database.
	Table = "node_log_targets"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "node_log_targets"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_log_targets"
)

// Columns holds all SQL columns for nodelogtarget fields.
var Columns = []string{
	FieldID,
	FieldPath,
	FieldType,
	FieldFormat,
	FieldLevel,
	FieldIsSyslog,
	FieldIsOff,
	FieldHasVariable,
	FieldSkipReason,
	FieldSize,
	FieldInode,
	FieldStatErr,
	FieldCapturedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "node_log_targets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"node_log_targets",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsSyslog holds the default value on creation for the "is_syslog" field.
	DefaultIsSyslog bool
	// DefaultIsOff holds the default value on creation for the "is_off" field.
	DefaultIsOff bool
	// DefaultHasVariable holds the default value on creation for the "has_variable" field.
	DefaultHasVariable bool
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultInode holds the default value on creation for the "inode" field.
	DefaultInode uint64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeAccess Type = "access"
	TypeError  Type = "error"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeAccess, TypeError:
		return nil
	default:
		return fmt.Errorf("nodelogtarget: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the NodeLogTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByIsSyslog orders the results by the is_syslog field.
func ByIsSyslog(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSyslog, opts...).ToFunc()
}

// ByIsOff orders the results by the is_off field.
func ByIsOff(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOff, opts...).ToFunc()
}

// ByHasVariable orders the results by the has_variable field.
func ByHasVariable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasVariable, opts...).ToFunc()
}

// BySkipReason orders the results by the skip_reason field.
func BySkipReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipReason, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByInode orders the results by the inode field.
func ByInode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInode, opts...).ToFunc()
}

// ByStatErr orders the results by the stat_err field.
func ByStatErr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatErr, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
