// Code generated by ent, DO NOT EDIT.

package nodelogtarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/th/ngxcp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldID, id))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldPath, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldFormat, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldLevel, v))
}

// IsSyslog applies equality check predicate on the "is_syslog" field. It's identical to IsSyslogEQ.
func IsSyslog(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldIsSyslog, v))
}

// IsOff applies equality check predicate on the "is_off" field. It's identical to IsOffEQ.
func IsOff(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldIsOff, v))
}

// HasVariable applies equality check predicate on the "has_variable" field. It's identical to HasVariableEQ.
func HasVariable(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldHasVariable, v))
}

// SkipReason applies equality check predicate on the "skip_reason" field. It's identical to SkipReasonEQ.
func SkipReason(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldSkipReason, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldSize, v))
}

// Inode applies equality check predicate on the "inode" field. It's identical to InodeEQ.
func Inode(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldInode, v))
}

// StatErr applies equality check predicate on the "stat_err" field. It's identical to StatErrEQ.
func StatErr(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldStatErr, v))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldCapturedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContainsFold(FieldPath, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldType, vs...))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatIsNil applies the IsNil predicate on the "format" field.
func FormatIsNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIsNull(FieldFormat))
}

// FormatNotNil applies the NotNil predicate on the "format" field.
func FormatNotNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotNull(FieldFormat))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContainsFold(FieldFormat, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldLevel, v))
}

// LevelContains applies the Contains predicate on the "level" field.
func LevelContains(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContains(FieldLevel, v))
}

// LevelHasPrefix applies the HasPrefix predicate on the "level" field.
func LevelHasPrefix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasPrefix(FieldLevel, v))
}

// LevelHasSuffix applies the HasSuffix predicate on the "level" field.
func LevelHasSuffix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasSuffix(FieldLevel, v))
}

// LevelIsNil applies the IsNil predicate on the "level" field.
func LevelIsNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIsNull(FieldLevel))
}

// LevelNotNil applies the NotNil predicate on the "level" field.
func LevelNotNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotNull(FieldLevel))
}

// LevelEqualFold applies the EqualFold predicate on the "level" field.
func LevelEqualFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEqualFold(FieldLevel, v))
}

// LevelContainsFold applies the ContainsFold predicate on the "level" field.
func LevelContainsFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContainsFold(FieldLevel, v))
}

// IsSyslogEQ applies the EQ predicate on the "is_syslog" field.
func IsSyslogEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldIsSyslog, v))
}

// IsSyslogNEQ applies the NEQ predicate on the "is_syslog" field.
func IsSyslogNEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldIsSyslog, v))
}

// IsOffEQ applies the EQ predicate on the "is_off" field.
func IsOffEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldIsOff, v))
}

// IsOffNEQ applies the NEQ predicate on the "is_off" field.
func IsOffNEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldIsOff, v))
}

// HasVariableEQ applies the EQ predicate on the "has_variable" field.
func HasVariableEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldHasVariable, v))
}

// HasVariableNEQ applies the NEQ predicate on the "has_variable" field.
func HasVariableNEQ(v bool) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldHasVariable, v))
}

// SkipReasonEQ applies the EQ predicate on the "skip_reason" field.
func SkipReasonEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldSkipReason, v))
}

// SkipReasonNEQ applies the NEQ predicate on the "skip_reason" field.
func SkipReasonNEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldSkipReason, v))
}

// SkipReasonIn applies the In predicate on the "skip_reason" field.
func SkipReasonIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldSkipReason, vs...))
}

// SkipReasonNotIn applies the NotIn predicate on the "skip_reason" field.
func SkipReasonNotIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldSkipReason, vs...))
}

// SkipReasonGT applies the GT predicate on the "skip_reason" field.
func SkipReasonGT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldSkipReason, v))
}

// SkipReasonGTE applies the GTE predicate on the "skip_reason" field.
func SkipReasonGTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldSkipReason, v))
}

// SkipReasonLT applies the LT predicate on the "skip_reason" field.
func SkipReasonLT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldSkipReason, v))
}

// SkipReasonLTE applies the LTE predicate on the "skip_reason" field.
func SkipReasonLTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldSkipReason, v))
}

// SkipReasonContains applies the Contains predicate on the "skip_reason" field.
func SkipReasonContains(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContains(FieldSkipReason, v))
}

// SkipReasonHasPrefix applies the HasPrefix predicate on the "skip_reason" field.
func SkipReasonHasPrefix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasPrefix(FieldSkipReason, v))
}

// SkipReasonHasSuffix applies the HasSuffix predicate on the "skip_reason" field.
func SkipReasonHasSuffix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasSuffix(FieldSkipReason, v))
}

// SkipReasonIsNil applies the IsNil predicate on the "skip_reason" field.
func SkipReasonIsNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIsNull(FieldSkipReason))
}

// SkipReasonNotNil applies the NotNil predicate on the "skip_reason" field.
func SkipReasonNotNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotNull(FieldSkipReason))
}

// SkipReasonEqualFold applies the EqualFold predicate on the "skip_reason" field.
func SkipReasonEqualFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEqualFold(FieldSkipReason, v))
}

// SkipReasonContainsFold applies the ContainsFold predicate on the "skip_reason" field.
func SkipReasonContainsFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContainsFold(FieldSkipReason, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldSize, v))
}

// InodeEQ applies the EQ predicate on the "inode" field.
func InodeEQ(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldInode, v))
}

// InodeNEQ applies the NEQ predicate on the "inode" field.
func InodeNEQ(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldInode, v))
}

// InodeIn applies the In predicate on the "inode" field.
func InodeIn(vs ...uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldInode, vs...))
}

// InodeNotIn applies the NotIn predicate on the "inode" field.
func InodeNotIn(vs ...uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldInode, vs...))
}

// InodeGT applies the GT predicate on the "inode" field.
func InodeGT(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldInode, v))
}

// InodeGTE applies the GTE predicate on the "inode" field.
func InodeGTE(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldInode, v))
}

// InodeLT applies the LT predicate on the "inode" field.
func InodeLT(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldInode, v))
}

// InodeLTE applies the LTE predicate on the "inode" field.
func InodeLTE(v uint64) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldInode, v))
}

// StatErrEQ applies the EQ predicate on the "stat_err" field.
func StatErrEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldStatErr, v))
}

// StatErrNEQ applies the NEQ predicate on the "stat_err" field.
func StatErrNEQ(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldStatErr, v))
}

// StatErrIn applies the In predicate on the "stat_err" field.
func StatErrIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldStatErr, vs...))
}

// StatErrNotIn applies the NotIn predicate on the "stat_err" field.
func StatErrNotIn(vs ...string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldStatErr, vs...))
}

// StatErrGT applies the GT predicate on the "stat_err" field.
func StatErrGT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldStatErr, v))
}

// StatErrGTE applies the GTE predicate on the "stat_err" field.
func StatErrGTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldStatErr, v))
}

// StatErrLT applies the LT predicate on the "stat_err" field.
func StatErrLT(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldStatErr, v))
}

// StatErrLTE applies the LTE predicate on the "stat_err" field.
func StatErrLTE(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldStatErr, v))
}

// StatErrContains applies the Contains predicate on the "stat_err" field.
func StatErrContains(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContains(FieldStatErr, v))
}

// StatErrHasPrefix applies the HasPrefix predicate on the "stat_err" field.
func StatErrHasPrefix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasPrefix(FieldStatErr, v))
}

// StatErrHasSuffix applies the HasSuffix predicate on the "stat_err" field.
func StatErrHasSuffix(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldHasSuffix(FieldStatErr, v))
}

// StatErrIsNil applies the IsNil predicate on the "stat_err" field.
func StatErrIsNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIsNull(FieldStatErr))
}

// StatErrNotNil applies the NotNil predicate on the "stat_err" field.
func StatErrNotNil() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotNull(FieldStatErr))
}

// StatErrEqualFold applies the EqualFold predicate on the "stat_err" field.
func StatErrEqualFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEqualFold(FieldStatErr, v))
}

// StatErrContainsFold applies the ContainsFold predicate on the "stat_err" field.
func StatErrContainsFold(v string) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldContainsFold(FieldStatErr, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldCapturedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.NodeLogTarget {
	return predicate.NodeLogTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodeLogTarget) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodeLogTarget) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodeLogTarget) predicate.NodeLogTarget {
	return predicate.NodeLogTarget(sql.NotPredicates(p))
}
