// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/changeorder"
	"github.com/th/ngxcp/ent/predicate"
)

// ChangeOrderDelete is the builder for deleting a ChangeOrder entity.
type ChangeOrderDelete struct {
	config
	hooks    []Hook
	mutation *ChangeOrderMutation
}

// Where appends a list predicates to the ChangeOrderDelete builder.
func (_d *ChangeOrderDelete) Where(ps ...predicate.ChangeOrder) *ChangeOrderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChangeOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChangeOrderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChangeOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(changeorder.Table, sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChangeOrderDeleteOne is the builder for deleting a single ChangeOrder entity.
type ChangeOrderDeleteOne struct {
	_d *ChangeOrderDelete
}

// Where appends a list predicates to the ChangeOrderDelete builder.
func (_d *ChangeOrderDeleteOne) Where(ps ...predicate.ChangeOrder) *ChangeOrderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChangeOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{changeorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChangeOrderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
