// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/configblob"
	"github.com/th/ngxcp/ent/configfile"
	"github.com/th/ngxcp/ent/configrevision"
	"github.com/th/ngxcp/ent/predicate"
)

// ConfigRevisionUpdate is the builder for updating ConfigRevision entities.
type ConfigRevisionUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigRevisionMutation
}

// Where appends a list predicates to the ConfigRevisionUpdate builder.
func (_u *ConfigRevisionUpdate) Where(ps ...predicate.ConfigRevision) *ConfigRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *ConfigRevisionUpdate) SetNodeID(v int) *ConfigRevisionUpdate {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableNodeID(v *int) *ConfigRevisionUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *ConfigRevisionUpdate) AddNodeID(v int) *ConfigRevisionUpdate {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *ConfigRevisionUpdate) SetPath(v string) *ConfigRevisionUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillablePath(v *string) *ConfigRevisionUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ConfigRevisionUpdate) SetMessage(v string) *ConfigRevisionUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableMessage(v *string) *ConfigRevisionUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ConfigRevisionUpdate) ClearMessage() *ConfigRevisionUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ConfigRevisionUpdate) SetAuthor(v string) *ConfigRevisionUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableAuthor(v *string) *ConfigRevisionUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *ConfigRevisionUpdate) ClearAuthor() *ConfigRevisionUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetBlobID sets the "blob" edge to the ConfigBlob entity by ID.
func (_u *ConfigRevisionUpdate) SetBlobID(id int) *ConfigRevisionUpdate {
	_u.mutation.SetBlobID(id)
	return _u
}

// SetNillableBlobID sets the "blob" edge to the ConfigBlob entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableBlobID(id *int) *ConfigRevisionUpdate {
	if id != nil {
		_u = _u.SetBlobID(*id)
	}
	return _u
}

// SetBlob sets the "blob" edge to the ConfigBlob entity.
func (_u *ConfigRevisionUpdate) SetBlob(v *ConfigBlob) *ConfigRevisionUpdate {
	return _u.SetBlobID(v.ID)
}

// SetParentID sets the "parent" edge to the ConfigRevision entity by ID.
func (_u *ConfigRevisionUpdate) SetParentID(id int) *ConfigRevisionUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the ConfigRevision entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableParentID(id *int) *ConfigRevisionUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the ConfigRevision entity.
func (_u *ConfigRevisionUpdate) SetParent(v *ConfigRevision) *ConfigRevisionUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the ConfigRevision entity by IDs.
func (_u *ConfigRevisionUpdate) AddChildIDs(ids ...int) *ConfigRevisionUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the ConfigRevision entity.
func (_u *ConfigRevisionUpdate) AddChildren(v ...*ConfigRevision) *ConfigRevisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetConfigFileID sets the "config_file" edge to the ConfigFile entity by ID.
func (_u *ConfigRevisionUpdate) SetConfigFileID(id int) *ConfigRevisionUpdate {
	_u.mutation.SetConfigFileID(id)
	return _u
}

// SetNillableConfigFileID sets the "config_file" edge to the ConfigFile entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdate) SetNillableConfigFileID(id *int) *ConfigRevisionUpdate {
	if id != nil {
		_u = _u.SetConfigFileID(*id)
	}
	return _u
}

// SetConfigFile sets the "config_file" edge to the ConfigFile entity.
func (_u *ConfigRevisionUpdate) SetConfigFile(v *ConfigFile) *ConfigRevisionUpdate {
	return _u.SetConfigFileID(v.ID)
}

// Mutation returns the ConfigRevisionMutation object of the builder.
func (_u *ConfigRevisionUpdate) Mutation() *ConfigRevisionMutation {
	return _u.mutation
}

// ClearBlob clears the "blob" edge to the ConfigBlob entity.
func (_u *ConfigRevisionUpdate) ClearBlob() *ConfigRevisionUpdate {
	_u.mutation.ClearBlob()
	return _u
}

// ClearParent clears the "parent" edge to the ConfigRevision entity.
func (_u *ConfigRevisionUpdate) ClearParent() *ConfigRevisionUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the ConfigRevision entity.
func (_u *ConfigRevisionUpdate) ClearChildren() *ConfigRevisionUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to ConfigRevision entities by IDs.
func (_u *ConfigRevisionUpdate) RemoveChildIDs(ids ...int) *ConfigRevisionUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to ConfigRevision entities.
func (_u *ConfigRevisionUpdate) RemoveChildren(v ...*ConfigRevision) *ConfigRevisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearConfigFile clears the "config_file" edge to the ConfigFile entity.
func (_u *ConfigRevisionUpdate) ClearConfigFile() *ConfigRevisionUpdate {
	_u.mutation.ClearConfigFile()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigRevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConfigRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(configrevision.Table, configrevision.Columns, sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(configrevision.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(configrevision.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(configrevision.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(configrevision.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(configrevision.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(configrevision.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(configrevision.FieldAuthor, field.TypeString)
	}
	if _u.mutation.BlobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.BlobTable,
			Columns: []string{configrevision.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configblob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.BlobTable,
			Columns: []string{configrevision.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configblob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.ParentTable,
			Columns: []string{configrevision.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.ParentTable,
			Columns: []string{configrevision.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configrevision.ConfigFileTable,
			Columns: []string{configrevision.ConfigFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configrevision.ConfigFileTable,
			Columns: []string{configrevision.ConfigFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigRevisionUpdateOne is the builder for updating a single ConfigRevision entity.
type ConfigRevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigRevisionMutation
}

// SetNodeID sets the "node_id" field.
func (_u *ConfigRevisionUpdateOne) SetNodeID(v int) *ConfigRevisionUpdateOne {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableNodeID(v *int) *ConfigRevisionUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *ConfigRevisionUpdateOne) AddNodeID(v int) *ConfigRevisionUpdateOne {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *ConfigRevisionUpdateOne) SetPath(v string) *ConfigRevisionUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillablePath(v *string) *ConfigRevisionUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ConfigRevisionUpdateOne) SetMessage(v string) *ConfigRevisionUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableMessage(v *string) *ConfigRevisionUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ConfigRevisionUpdateOne) ClearMessage() *ConfigRevisionUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ConfigRevisionUpdateOne) SetAuthor(v string) *ConfigRevisionUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableAuthor(v *string) *ConfigRevisionUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *ConfigRevisionUpdateOne) ClearAuthor() *ConfigRevisionUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetBlobID sets the "blob" edge to the ConfigBlob entity by ID.
func (_u *ConfigRevisionUpdateOne) SetBlobID(id int) *ConfigRevisionUpdateOne {
	_u.mutation.SetBlobID(id)
	return _u
}

// SetNillableBlobID sets the "blob" edge to the ConfigBlob entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableBlobID(id *int) *ConfigRevisionUpdateOne {
	if id != nil {
		_u = _u.SetBlobID(*id)
	}
	return _u
}

// SetBlob sets the "blob" edge to the ConfigBlob entity.
func (_u *ConfigRevisionUpdateOne) SetBlob(v *ConfigBlob) *ConfigRevisionUpdateOne {
	return _u.SetBlobID(v.ID)
}

// SetParentID sets the "parent" edge to the ConfigRevision entity by ID.
func (_u *ConfigRevisionUpdateOne) SetParentID(id int) *ConfigRevisionUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the ConfigRevision entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableParentID(id *int) *ConfigRevisionUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the ConfigRevision entity.
func (_u *ConfigRevisionUpdateOne) SetParent(v *ConfigRevision) *ConfigRevisionUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the ConfigRevision entity by IDs.
func (_u *ConfigRevisionUpdateOne) AddChildIDs(ids ...int) *ConfigRevisionUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the ConfigRevision entity.
func (_u *ConfigRevisionUpdateOne) AddChildren(v ...*ConfigRevision) *ConfigRevisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetConfigFileID sets the "config_file" edge to the ConfigFile entity by ID.
func (_u *ConfigRevisionUpdateOne) SetConfigFileID(id int) *ConfigRevisionUpdateOne {
	_u.mutation.SetConfigFileID(id)
	return _u
}

// SetNillableConfigFileID sets the "config_file" edge to the ConfigFile entity by ID if the given value is not nil.
func (_u *ConfigRevisionUpdateOne) SetNillableConfigFileID(id *int) *ConfigRevisionUpdateOne {
	if id != nil {
		_u = _u.SetConfigFileID(*id)
	}
	return _u
}

// SetConfigFile sets the "config_file" edge to the ConfigFile entity.
func (_u *ConfigRevisionUpdateOne) SetConfigFile(v *ConfigFile) *ConfigRevisionUpdateOne {
	return _u.SetConfigFileID(v.ID)
}

// Mutation returns the ConfigRevisionMutation object of the builder.
func (_u *ConfigRevisionUpdateOne) Mutation() *ConfigRevisionMutation {
	return _u.mutation
}

// ClearBlob clears the "blob" edge to the ConfigBlob entity.
func (_u *ConfigRevisionUpdateOne) ClearBlob() *ConfigRevisionUpdateOne {
	_u.mutation.ClearBlob()
	return _u
}

// ClearParent clears the "parent" edge to the ConfigRevision entity.
func (_u *ConfigRevisionUpdateOne) ClearParent() *ConfigRevisionUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the ConfigRevision entity.
func (_u *ConfigRevisionUpdateOne) ClearChildren() *ConfigRevisionUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to ConfigRevision entities by IDs.
func (_u *ConfigRevisionUpdateOne) RemoveChildIDs(ids ...int) *ConfigRevisionUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to ConfigRevision entities.
func (_u *ConfigRevisionUpdateOne) RemoveChildren(v ...*ConfigRevision) *ConfigRevisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearConfigFile clears the "config_file" edge to the ConfigFile entity.
func (_u *ConfigRevisionUpdateOne) ClearConfigFile() *ConfigRevisionUpdateOne {
	_u.mutation.ClearConfigFile()
	return _u
}

// Where appends a list predicates to the ConfigRevisionUpdate builder.
func (_u *ConfigRevisionUpdateOne) Where(ps ...predicate.ConfigRevision) *ConfigRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigRevisionUpdateOne) Select(field string, fields ...string) *ConfigRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfigRevision entity.
func (_u *ConfigRevisionUpdateOne) Save(ctx context.Context) (*ConfigRevision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigRevisionUpdateOne) SaveX(ctx context.Context) *ConfigRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConfigRevisionUpdateOne) sqlSave(ctx context.Context) (_node *ConfigRevision, err error) {
	_spec := sqlgraph.NewUpdateSpec(configrevision.Table, configrevision.Columns, sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfigRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configrevision.FieldID)
		for _, f := range fields {
			if !configrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(configrevision.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(configrevision.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(configrevision.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(configrevision.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(configrevision.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(configrevision.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(configrevision.FieldAuthor, field.TypeString)
	}
	if _u.mutation.BlobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.BlobTable,
			Columns: []string{configrevision.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configblob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.BlobTable,
			Columns: []string{configrevision.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configblob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.ParentTable,
			Columns: []string{configrevision.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   configrevision.ParentTable,
			Columns: []string{configrevision.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   configrevision.ChildrenTable,
			Columns: []string{configrevision.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configrevision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configrevision.ConfigFileTable,
			Columns: []string{configrevision.ConfigFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configrevision.ConfigFileTable,
			Columns: []string{configrevision.ConfigFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConfigRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
