// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/th/ngxcp/ent/configblob"
	"github.com/th/ngxcp/ent/configrevision"
)

// ConfigRevision is the model entity for the ConfigRevision schema.
type ConfigRevision struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID int `json:"node_id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Source holds the value of the "source" field.
	Source configrevision.Source `json:"source,omitempty"`
	// ChangeOrderID holds the value of the "change_order_id" field.
	ChangeOrderID int `json:"change_order_id,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Author holds the value of the "author" field.
	Author string `json:"author,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConfigRevisionQuery when eager-loading is set.
	Edges                    ConfigRevisionEdges `json:"edges"`
	config_blob_revisions    *int
	config_revision_children *int
	selectValues             sql.SelectValues
}

// ConfigRevisionEdges holds the relations/edges for other nodes in the graph.
type ConfigRevisionEdges struct {
	// Blob holds the value of the blob edge.
	Blob *ConfigBlob `json:"blob,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *ConfigRevision `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*ConfigRevision `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// BlobOrErr returns the Blob value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConfigRevisionEdges) BlobOrErr() (*ConfigBlob, error) {
	if e.Blob != nil {
		return e.Blob, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: configblob.Label}
	}
	return nil, &NotLoadedError{edge: "blob"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConfigRevisionEdges) ParentOrErr() (*ConfigRevision, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: configrevision.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e ConfigRevisionEdges) ChildrenOrErr() ([]*ConfigRevision, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConfigRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configrevision.FieldID, configrevision.FieldNodeID, configrevision.FieldChangeOrderID:
			values[i] = new(sql.NullInt64)
		case configrevision.FieldPath, configrevision.FieldSource, configrevision.FieldMessage, configrevision.FieldAuthor:
			values[i] = new(sql.NullString)
		case configrevision.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case configrevision.ForeignKeys[0]: // config_blob_revisions
			values[i] = new(sql.NullInt64)
		case configrevision.ForeignKeys[1]: // config_revision_children
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConfigRevision fields.
func (_m *ConfigRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configrevision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case configrevision.FieldNodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = int(value.Int64)
			}
		case configrevision.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case configrevision.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = configrevision.Source(value.String)
			}
		case configrevision.FieldChangeOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field change_order_id", values[i])
			} else if value.Valid {
				_m.ChangeOrderID = int(value.Int64)
			}
		case configrevision.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case configrevision.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = value.String
			}
		case configrevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case configrevision.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field config_blob_revisions", value)
			} else if value.Valid {
				_m.config_blob_revisions = new(int)
				*_m.config_blob_revisions = int(value.Int64)
			}
		case configrevision.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field config_revision_children", value)
			} else if value.Valid {
				_m.config_revision_children = new(int)
				*_m.config_revision_children = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConfigRevision.
// This includes values selected through modifiers, order, etc.
func (_m *ConfigRevision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBlob queries the "blob" edge of the ConfigRevision entity.
func (_m *ConfigRevision) QueryBlob() *ConfigBlobQuery {
	return NewConfigRevisionClient(_m.config).QueryBlob(_m)
}

// QueryParent queries the "parent" edge of the ConfigRevision entity.
func (_m *ConfigRevision) QueryParent() *ConfigRevisionQuery {
	return NewConfigRevisionClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the ConfigRevision entity.
func (_m *ConfigRevision) QueryChildren() *ConfigRevisionQuery {
	return NewConfigRevisionClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this ConfigRevision.
// Note that you need to call ConfigRevision.Unwrap() before calling this method if this ConfigRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConfigRevision) Update() *ConfigRevisionUpdateOne {
	return NewConfigRevisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConfigRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConfigRevision) Unwrap() *ConfigRevision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConfigRevision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConfigRevision) String() string {
	var builder strings.Builder
	builder.WriteString("ConfigRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("node_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeID))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("change_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChangeOrderID))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("author=")
	builder.WriteString(_m.Author)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConfigRevisions is a parsable slice of ConfigRevision.
type ConfigRevisions []*ConfigRevision
