// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/changeorder"
	"github.com/th/ngxcp/ent/deploytask"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/predicate"
)

// DeployTaskUpdate is the builder for updating DeployTask entities.
type DeployTaskUpdate struct {
	config
	hooks    []Hook
	mutation *DeployTaskMutation
}

// Where appends a list predicates to the DeployTaskUpdate builder.
func (_u *DeployTaskUpdate) Where(ps ...predicate.DeployTask) *DeployTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *DeployTaskUpdate) SetState(v deploytask.State) *DeployTaskUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableState(v *deploytask.State) *DeployTaskUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *DeployTaskUpdate) SetPhase(v deploytask.Phase) *DeployTaskUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillablePhase(v *deploytask.Phase) *DeployTaskUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// ClearPhase clears the value of the "phase" field.
func (_u *DeployTaskUpdate) ClearPhase() *DeployTaskUpdate {
	_u.mutation.ClearPhase()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *DeployTaskUpdate) SetAttempts(v int) *DeployTaskUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableAttempts(v *int) *DeployTaskUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *DeployTaskUpdate) AddAttempts(v int) *DeployTaskUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *DeployTaskUpdate) SetErrorDetail(v string) *DeployTaskUpdate {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableErrorDetail(v *string) *DeployTaskUpdate {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *DeployTaskUpdate) ClearErrorDetail() *DeployTaskUpdate {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeployTaskUpdate) SetStartedAt(v time.Time) *DeployTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableStartedAt(v *time.Time) *DeployTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeployTaskUpdate) ClearStartedAt() *DeployTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeployTaskUpdate) SetFinishedAt(v time.Time) *DeployTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableFinishedAt(v *time.Time) *DeployTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeployTaskUpdate) ClearFinishedAt() *DeployTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployTaskUpdate) SetUpdatedAt(v time.Time) *DeployTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DeployTaskUpdate) SetDeletedAt(v time.Time) *DeployTaskUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableDeletedAt(v *time.Time) *DeployTaskUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DeployTaskUpdate) ClearDeletedAt() *DeployTaskUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *DeployTaskUpdate) SetNodeID(id int) *DeployTaskUpdate {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableNodeID(id *int) *DeployTaskUpdate {
	if id != nil {
		_u = _u.SetNodeID(*id)
	}
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *DeployTaskUpdate) SetNode(v *Node) *DeployTaskUpdate {
	return _u.SetNodeID(v.ID)
}

// SetChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID.
func (_u *DeployTaskUpdate) SetChangeOrderID(id int) *DeployTaskUpdate {
	_u.mutation.SetChangeOrderID(id)
	return _u
}

// SetNillableChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID if the given value is not nil.
func (_u *DeployTaskUpdate) SetNillableChangeOrderID(id *int) *DeployTaskUpdate {
	if id != nil {
		_u = _u.SetChangeOrderID(*id)
	}
	return _u
}

// SetChangeOrder sets the "change_order" edge to the ChangeOrder entity.
func (_u *DeployTaskUpdate) SetChangeOrder(v *ChangeOrder) *DeployTaskUpdate {
	return _u.SetChangeOrderID(v.ID)
}

// Mutation returns the DeployTaskMutation object of the builder.
func (_u *DeployTaskUpdate) Mutation() *DeployTaskMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *DeployTaskUpdate) ClearNode() *DeployTaskUpdate {
	_u.mutation.ClearNode()
	return _u
}

// ClearChangeOrder clears the "change_order" edge to the ChangeOrder entity.
func (_u *DeployTaskUpdate) ClearChangeOrder() *DeployTaskUpdate {
	_u.mutation.ClearChangeOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeployTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeployTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploytask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployTaskUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := deploytask.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "DeployTask.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := deploytask.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "DeployTask.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploytask.Table, deploytask.Columns, sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deploytask.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(deploytask.FieldPhase, field.TypeEnum, value)
	}
	if _u.mutation.PhaseCleared() {
		_spec.ClearField(deploytask.FieldPhase, field.TypeEnum)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(deploytask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(deploytask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(deploytask.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(deploytask.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploytask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploytask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deploytask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deploytask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploytask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(deploytask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(deploytask.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.NodeTable,
			Columns: []string{deploytask.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.NodeTable,
			Columns: []string{deploytask.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.ChangeOrderTable,
			Columns: []string{deploytask.ChangeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.ChangeOrderTable,
			Columns: []string{deploytask.ChangeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeployTaskUpdateOne is the builder for updating a single DeployTask entity.
type DeployTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeployTaskMutation
}

// SetState sets the "state" field.
func (_u *DeployTaskUpdateOne) SetState(v deploytask.State) *DeployTaskUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableState(v *deploytask.State) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *DeployTaskUpdateOne) SetPhase(v deploytask.Phase) *DeployTaskUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillablePhase(v *deploytask.Phase) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// ClearPhase clears the value of the "phase" field.
func (_u *DeployTaskUpdateOne) ClearPhase() *DeployTaskUpdateOne {
	_u.mutation.ClearPhase()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *DeployTaskUpdateOne) SetAttempts(v int) *DeployTaskUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableAttempts(v *int) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *DeployTaskUpdateOne) AddAttempts(v int) *DeployTaskUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetErrorDetail sets the "error_detail" field.
func (_u *DeployTaskUpdateOne) SetErrorDetail(v string) *DeployTaskUpdateOne {
	_u.mutation.SetErrorDetail(v)
	return _u
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableErrorDetail(v *string) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetErrorDetail(*v)
	}
	return _u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (_u *DeployTaskUpdateOne) ClearErrorDetail() *DeployTaskUpdateOne {
	_u.mutation.ClearErrorDetail()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeployTaskUpdateOne) SetStartedAt(v time.Time) *DeployTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableStartedAt(v *time.Time) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeployTaskUpdateOne) ClearStartedAt() *DeployTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeployTaskUpdateOne) SetFinishedAt(v time.Time) *DeployTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeployTaskUpdateOne) ClearFinishedAt() *DeployTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployTaskUpdateOne) SetUpdatedAt(v time.Time) *DeployTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DeployTaskUpdateOne) SetDeletedAt(v time.Time) *DeployTaskUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableDeletedAt(v *time.Time) *DeployTaskUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DeployTaskUpdateOne) ClearDeletedAt() *DeployTaskUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *DeployTaskUpdateOne) SetNodeID(id int) *DeployTaskUpdateOne {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableNodeID(id *int) *DeployTaskUpdateOne {
	if id != nil {
		_u = _u.SetNodeID(*id)
	}
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *DeployTaskUpdateOne) SetNode(v *Node) *DeployTaskUpdateOne {
	return _u.SetNodeID(v.ID)
}

// SetChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID.
func (_u *DeployTaskUpdateOne) SetChangeOrderID(id int) *DeployTaskUpdateOne {
	_u.mutation.SetChangeOrderID(id)
	return _u
}

// SetNillableChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID if the given value is not nil.
func (_u *DeployTaskUpdateOne) SetNillableChangeOrderID(id *int) *DeployTaskUpdateOne {
	if id != nil {
		_u = _u.SetChangeOrderID(*id)
	}
	return _u
}

// SetChangeOrder sets the "change_order" edge to the ChangeOrder entity.
func (_u *DeployTaskUpdateOne) SetChangeOrder(v *ChangeOrder) *DeployTaskUpdateOne {
	return _u.SetChangeOrderID(v.ID)
}

// Mutation returns the DeployTaskMutation object of the builder.
func (_u *DeployTaskUpdateOne) Mutation() *DeployTaskMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *DeployTaskUpdateOne) ClearNode() *DeployTaskUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// ClearChangeOrder clears the "change_order" edge to the ChangeOrder entity.
func (_u *DeployTaskUpdateOne) ClearChangeOrder() *DeployTaskUpdateOne {
	_u.mutation.ClearChangeOrder()
	return _u
}

// Where appends a list predicates to the DeployTaskUpdate builder.
func (_u *DeployTaskUpdateOne) Where(ps ...predicate.DeployTask) *DeployTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeployTaskUpdateOne) Select(field string, fields ...string) *DeployTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeployTask entity.
func (_u *DeployTaskUpdateOne) Save(ctx context.Context) (*DeployTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployTaskUpdateOne) SaveX(ctx context.Context) *DeployTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeployTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploytask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployTaskUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := deploytask.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "DeployTask.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := deploytask.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "DeployTask.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployTaskUpdateOne) sqlSave(ctx context.Context) (_node *DeployTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploytask.Table, deploytask.Columns, sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeployTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploytask.FieldID)
		for _, f := range fields {
			if !deploytask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploytask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deploytask.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(deploytask.FieldPhase, field.TypeEnum, value)
	}
	if _u.mutation.PhaseCleared() {
		_spec.ClearField(deploytask.FieldPhase, field.TypeEnum)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(deploytask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(deploytask.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorDetail(); ok {
		_spec.SetField(deploytask.FieldErrorDetail, field.TypeString, value)
	}
	if _u.mutation.ErrorDetailCleared() {
		_spec.ClearField(deploytask.FieldErrorDetail, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploytask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploytask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deploytask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deploytask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploytask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(deploytask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(deploytask.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.NodeTable,
			Columns: []string{deploytask.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.NodeTable,
			Columns: []string{deploytask.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.ChangeOrderTable,
			Columns: []string{deploytask.ChangeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.ChangeOrderTable,
			Columns: []string{deploytask.ChangeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeployTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
