// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/deploynodelock"
	"github.com/th/ngxcp/ent/predicate"
)

// DeployNodeLockUpdate is the builder for updating DeployNodeLock entities.
type DeployNodeLockUpdate struct {
	config
	hooks    []Hook
	mutation *DeployNodeLockMutation
}

// Where appends a list predicates to the DeployNodeLockUpdate builder.
func (_u *DeployNodeLockUpdate) Where(ps ...predicate.DeployNodeLock) *DeployNodeLockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *DeployNodeLockUpdate) SetNodeID(v int) *DeployNodeLockUpdate {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *DeployNodeLockUpdate) SetNillableNodeID(v *int) *DeployNodeLockUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *DeployNodeLockUpdate) AddNodeID(v int) *DeployNodeLockUpdate {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *DeployNodeLockUpdate) SetOrderID(v int) *DeployNodeLockUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *DeployNodeLockUpdate) SetNillableOrderID(v *int) *DeployNodeLockUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *DeployNodeLockUpdate) AddOrderID(v int) *DeployNodeLockUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *DeployNodeLockUpdate) SetLockedAt(v time.Time) *DeployNodeLockUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *DeployNodeLockUpdate) SetNillableLockedAt(v *time.Time) *DeployNodeLockUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DeployNodeLockUpdate) SetExpiresAt(v time.Time) *DeployNodeLockUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DeployNodeLockUpdate) SetNillableExpiresAt(v *time.Time) *DeployNodeLockUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DeployNodeLockMutation object of the builder.
func (_u *DeployNodeLockUpdate) Mutation() *DeployNodeLockMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeployNodeLockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployNodeLockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeployNodeLockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployNodeLockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeployNodeLockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deploynodelock.Table, deploynodelock.Columns, sqlgraph.NewFieldSpec(deploynodelock.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(deploynodelock.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(deploynodelock.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(deploynodelock.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(deploynodelock.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(deploynodelock.FieldLockedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(deploynodelock.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploynodelock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeployNodeLockUpdateOne is the builder for updating a single DeployNodeLock entity.
type DeployNodeLockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeployNodeLockMutation
}

// SetNodeID sets the "node_id" field.
func (_u *DeployNodeLockUpdateOne) SetNodeID(v int) *DeployNodeLockUpdateOne {
	_u.mutation.ResetNodeID()
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *DeployNodeLockUpdateOne) SetNillableNodeID(v *int) *DeployNodeLockUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// AddNodeID adds value to the "node_id" field.
func (_u *DeployNodeLockUpdateOne) AddNodeID(v int) *DeployNodeLockUpdateOne {
	_u.mutation.AddNodeID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *DeployNodeLockUpdateOne) SetOrderID(v int) *DeployNodeLockUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *DeployNodeLockUpdateOne) SetNillableOrderID(v *int) *DeployNodeLockUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *DeployNodeLockUpdateOne) AddOrderID(v int) *DeployNodeLockUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *DeployNodeLockUpdateOne) SetLockedAt(v time.Time) *DeployNodeLockUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *DeployNodeLockUpdateOne) SetNillableLockedAt(v *time.Time) *DeployNodeLockUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DeployNodeLockUpdateOne) SetExpiresAt(v time.Time) *DeployNodeLockUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DeployNodeLockUpdateOne) SetNillableExpiresAt(v *time.Time) *DeployNodeLockUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DeployNodeLockMutation object of the builder.
func (_u *DeployNodeLockUpdateOne) Mutation() *DeployNodeLockMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeployNodeLockUpdate builder.
func (_u *DeployNodeLockUpdateOne) Where(ps ...predicate.DeployNodeLock) *DeployNodeLockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeployNodeLockUpdateOne) Select(field string, fields ...string) *DeployNodeLockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeployNodeLock entity.
func (_u *DeployNodeLockUpdateOne) Save(ctx context.Context) (*DeployNodeLock, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployNodeLockUpdateOne) SaveX(ctx context.Context) *DeployNodeLock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeployNodeLockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployNodeLockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeployNodeLockUpdateOne) sqlSave(ctx context.Context) (_node *DeployNodeLock, err error) {
	_spec := sqlgraph.NewUpdateSpec(deploynodelock.Table, deploynodelock.Columns, sqlgraph.NewFieldSpec(deploynodelock.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeployNodeLock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploynodelock.FieldID)
		for _, f := range fields {
			if !deploynodelock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploynodelock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(deploynodelock.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNodeID(); ok {
		_spec.AddField(deploynodelock.FieldNodeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(deploynodelock.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(deploynodelock.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(deploynodelock.FieldLockedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(deploynodelock.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &DeployNodeLock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploynodelock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
