// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/changeorder"
	"github.com/th/ngxcp/ent/deploytask"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/schema"
)

// DeployTaskCreate is the builder for creating a DeployTask entity.
type DeployTaskCreate struct {
	config
	mutation *DeployTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetState sets the "state" field.
func (_c *DeployTaskCreate) SetState(v deploytask.State) *DeployTaskCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableState(v *deploytask.State) *DeployTaskCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *DeployTaskCreate) SetPhase(v deploytask.Phase) *DeployTaskCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillablePhase(v *deploytask.Phase) *DeployTaskCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *DeployTaskCreate) SetAttempts(v int) *DeployTaskCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableAttempts(v *int) *DeployTaskCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetErrorDetail sets the "error_detail" field.
func (_c *DeployTaskCreate) SetErrorDetail(v string) *DeployTaskCreate {
	_c.mutation.SetErrorDetail(v)
	return _c
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableErrorDetail(v *string) *DeployTaskCreate {
	if v != nil {
		_c.SetErrorDetail(*v)
	}
	return _c
}

// SetSteps sets the "steps" field.
func (_c *DeployTaskCreate) SetSteps(v []schema.TaskStep) *DeployTaskCreate {
	_c.mutation.SetSteps(v)
	return _c
}

// SetCurrentStep sets the "current_step" field.
func (_c *DeployTaskCreate) SetCurrentStep(v int) *DeployTaskCreate {
	_c.mutation.SetCurrentStep(v)
	return _c
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableCurrentStep(v *int) *DeployTaskCreate {
	if v != nil {
		_c.SetCurrentStep(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DeployTaskCreate) SetStartedAt(v time.Time) *DeployTaskCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableStartedAt(v *time.Time) *DeployTaskCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *DeployTaskCreate) SetFinishedAt(v time.Time) *DeployTaskCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableFinishedAt(v *time.Time) *DeployTaskCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeployTaskCreate) SetCreatedAt(v time.Time) *DeployTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableCreatedAt(v *time.Time) *DeployTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeployTaskCreate) SetUpdatedAt(v time.Time) *DeployTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableUpdatedAt(v *time.Time) *DeployTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DeployTaskCreate) SetDeletedAt(v time.Time) *DeployTaskCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableDeletedAt(v *time.Time) *DeployTaskCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_c *DeployTaskCreate) SetNodeID(id int) *DeployTaskCreate {
	_c.mutation.SetNodeID(id)
	return _c
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableNodeID(id *int) *DeployTaskCreate {
	if id != nil {
		_c = _c.SetNodeID(*id)
	}
	return _c
}

// SetNode sets the "node" edge to the Node entity.
func (_c *DeployTaskCreate) SetNode(v *Node) *DeployTaskCreate {
	return _c.SetNodeID(v.ID)
}

// SetChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID.
func (_c *DeployTaskCreate) SetChangeOrderID(id int) *DeployTaskCreate {
	_c.mutation.SetChangeOrderID(id)
	return _c
}

// SetNillableChangeOrderID sets the "change_order" edge to the ChangeOrder entity by ID if the given value is not nil.
func (_c *DeployTaskCreate) SetNillableChangeOrderID(id *int) *DeployTaskCreate {
	if id != nil {
		_c = _c.SetChangeOrderID(*id)
	}
	return _c
}

// SetChangeOrder sets the "change_order" edge to the ChangeOrder entity.
func (_c *DeployTaskCreate) SetChangeOrder(v *ChangeOrder) *DeployTaskCreate {
	return _c.SetChangeOrderID(v.ID)
}

// Mutation returns the DeployTaskMutation object of the builder.
func (_c *DeployTaskCreate) Mutation() *DeployTaskMutation {
	return _c.mutation
}

// Save creates the DeployTask in the database.
func (_c *DeployTaskCreate) Save(ctx context.Context) (*DeployTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeployTaskCreate) SaveX(ctx context.Context) *DeployTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeployTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeployTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeployTaskCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := deploytask.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := deploytask.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CurrentStep(); !ok {
		v := deploytask.DefaultCurrentStep
		_c.mutation.SetCurrentStep(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deploytask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := deploytask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeployTaskCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "DeployTask.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := deploytask.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "DeployTask.state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := deploytask.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "DeployTask.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "DeployTask.attempts"`)}
	}
	if _, ok := _c.mutation.CurrentStep(); !ok {
		return &ValidationError{Name: "current_step", err: errors.New(`ent: missing required field "DeployTask.current_step"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeployTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeployTask.updated_at"`)}
	}
	return nil
}

func (_c *DeployTaskCreate) sqlSave(ctx context.Context) (*DeployTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeployTaskCreate) createSpec() (*DeployTask, *sqlgraph.CreateSpec) {
	var (
		_node = &DeployTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deploytask.Table, sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(deploytask.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(deploytask.FieldPhase, field.TypeEnum, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(deploytask.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ErrorDetail(); ok {
		_spec.SetField(deploytask.FieldErrorDetail, field.TypeString, value)
		_node.ErrorDetail = value
	}
	if value, ok := _c.mutation.Steps(); ok {
		_spec.SetField(deploytask.FieldSteps, field.TypeJSON, value)
		_node.Steps = value
	}
	if value, ok := _c.mutation.CurrentStep(); ok {
		_spec.SetField(deploytask.FieldCurrentStep, field.TypeInt, value)
		_node.CurrentStep = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(deploytask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(deploytask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deploytask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(deploytask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(deploytask.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.NodeTable,
			Columns: []string{deploytask.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.node_deploy_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploytask.ChangeOrderTable,
			Columns: []string{deploytask.ChangeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changeorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.change_order_deploy_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeployTask.Create().
//		SetState(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeployTaskUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *DeployTaskCreate) OnConflict(opts ...sql.ConflictOption) *DeployTaskUpsertOne {
	_c.conflict = opts
	return &DeployTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeployTaskCreate) OnConflictColumns(columns ...string) *DeployTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeployTaskUpsertOne{
		create: _c,
	}
}

type (
	// DeployTaskUpsertOne is the builder for "upsert"-ing
	//  one DeployTask node.
	DeployTaskUpsertOne struct {
		create *DeployTaskCreate
	}

	// DeployTaskUpsert is the "OnConflict" setter.
	DeployTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetState sets the "state" field.
func (u *DeployTaskUpsert) SetState(v deploytask.State) *DeployTaskUpsert {
	u.Set(deploytask.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateState() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldState)
	return u
}

// SetPhase sets the "phase" field.
func (u *DeployTaskUpsert) SetPhase(v deploytask.Phase) *DeployTaskUpsert {
	u.Set(deploytask.FieldPhase, v)
	return u
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdatePhase() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldPhase)
	return u
}

// ClearPhase clears the value of the "phase" field.
func (u *DeployTaskUpsert) ClearPhase() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldPhase)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *DeployTaskUpsert) SetAttempts(v int) *DeployTaskUpsert {
	u.Set(deploytask.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateAttempts() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *DeployTaskUpsert) AddAttempts(v int) *DeployTaskUpsert {
	u.Add(deploytask.FieldAttempts, v)
	return u
}

// SetErrorDetail sets the "error_detail" field.
func (u *DeployTaskUpsert) SetErrorDetail(v string) *DeployTaskUpsert {
	u.Set(deploytask.FieldErrorDetail, v)
	return u
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateErrorDetail() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldErrorDetail)
	return u
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *DeployTaskUpsert) ClearErrorDetail() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldErrorDetail)
	return u
}

// SetSteps sets the "steps" field.
func (u *DeployTaskUpsert) SetSteps(v []schema.TaskStep) *DeployTaskUpsert {
	u.Set(deploytask.FieldSteps, v)
	return u
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateSteps() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldSteps)
	return u
}

// ClearSteps clears the value of the "steps" field.
func (u *DeployTaskUpsert) ClearSteps() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldSteps)
	return u
}

// SetCurrentStep sets the "current_step" field.
func (u *DeployTaskUpsert) SetCurrentStep(v int) *DeployTaskUpsert {
	u.Set(deploytask.FieldCurrentStep, v)
	return u
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateCurrentStep() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldCurrentStep)
	return u
}

// AddCurrentStep adds v to the "current_step" field.
func (u *DeployTaskUpsert) AddCurrentStep(v int) *DeployTaskUpsert {
	u.Add(deploytask.FieldCurrentStep, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *DeployTaskUpsert) SetStartedAt(v time.Time) *DeployTaskUpsert {
	u.Set(deploytask.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateStartedAt() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DeployTaskUpsert) ClearStartedAt() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeployTaskUpsert) SetFinishedAt(v time.Time) *DeployTaskUpsert {
	u.Set(deploytask.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateFinishedAt() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeployTaskUpsert) ClearFinishedAt() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldFinishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeployTaskUpsert) SetUpdatedAt(v time.Time) *DeployTaskUpsert {
	u.Set(deploytask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateUpdatedAt() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DeployTaskUpsert) SetDeletedAt(v time.Time) *DeployTaskUpsert {
	u.Set(deploytask.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DeployTaskUpsert) UpdateDeletedAt() *DeployTaskUpsert {
	u.SetExcluded(deploytask.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DeployTaskUpsert) ClearDeletedAt() *DeployTaskUpsert {
	u.SetNull(deploytask.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeployTaskUpsertOne) UpdateNewValues() *DeployTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(deploytask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeployTaskUpsertOne) Ignore() *DeployTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeployTaskUpsertOne) DoNothing() *DeployTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeployTaskCreate.OnConflict
// documentation for more info.
func (u *DeployTaskUpsertOne) Update(set func(*DeployTaskUpsert)) *DeployTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeployTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *DeployTaskUpsertOne) SetState(v deploytask.State) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateState() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateState()
	})
}

// SetPhase sets the "phase" field.
func (u *DeployTaskUpsertOne) SetPhase(v deploytask.Phase) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdatePhase() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdatePhase()
	})
}

// ClearPhase clears the value of the "phase" field.
func (u *DeployTaskUpsertOne) ClearPhase() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearPhase()
	})
}

// SetAttempts sets the "attempts" field.
func (u *DeployTaskUpsertOne) SetAttempts(v int) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *DeployTaskUpsertOne) AddAttempts(v int) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateAttempts() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateAttempts()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *DeployTaskUpsertOne) SetErrorDetail(v string) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateErrorDetail() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *DeployTaskUpsertOne) ClearErrorDetail() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearErrorDetail()
	})
}

// SetSteps sets the "steps" field.
func (u *DeployTaskUpsertOne) SetSteps(v []schema.TaskStep) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateSteps() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateSteps()
	})
}

// ClearSteps clears the value of the "steps" field.
func (u *DeployTaskUpsertOne) ClearSteps() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearSteps()
	})
}

// SetCurrentStep sets the "current_step" field.
func (u *DeployTaskUpsertOne) SetCurrentStep(v int) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetCurrentStep(v)
	})
}

// AddCurrentStep adds v to the "current_step" field.
func (u *DeployTaskUpsertOne) AddCurrentStep(v int) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.AddCurrentStep(v)
	})
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateCurrentStep() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateCurrentStep()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *DeployTaskUpsertOne) SetStartedAt(v time.Time) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateStartedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DeployTaskUpsertOne) ClearStartedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeployTaskUpsertOne) SetFinishedAt(v time.Time) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateFinishedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeployTaskUpsertOne) ClearFinishedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeployTaskUpsertOne) SetUpdatedAt(v time.Time) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateUpdatedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DeployTaskUpsertOne) SetDeletedAt(v time.Time) *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DeployTaskUpsertOne) UpdateDeletedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DeployTaskUpsertOne) ClearDeletedAt() *DeployTaskUpsertOne {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *DeployTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeployTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeployTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeployTaskUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeployTaskUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeployTaskCreateBulk is the builder for creating many DeployTask entities in bulk.
type DeployTaskCreateBulk struct {
	config
	err      error
	builders []*DeployTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the DeployTask entities in the database.
func (_c *DeployTaskCreateBulk) Save(ctx context.Context) ([]*DeployTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeployTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeployTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeployTaskCreateBulk) SaveX(ctx context.Context) []*DeployTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeployTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeployTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeployTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeployTaskUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *DeployTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeployTaskUpsertBulk {
	_c.conflict = opts
	return &DeployTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeployTaskCreateBulk) OnConflictColumns(columns ...string) *DeployTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeployTaskUpsertBulk{
		create: _c,
	}
}

// DeployTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of DeployTask nodes.
type DeployTaskUpsertBulk struct {
	create *DeployTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeployTaskUpsertBulk) UpdateNewValues() *DeployTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(deploytask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeployTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeployTaskUpsertBulk) Ignore() *DeployTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeployTaskUpsertBulk) DoNothing() *DeployTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeployTaskCreateBulk.OnConflict
// documentation for more info.
func (u *DeployTaskUpsertBulk) Update(set func(*DeployTaskUpsert)) *DeployTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeployTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *DeployTaskUpsertBulk) SetState(v deploytask.State) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateState() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateState()
	})
}

// SetPhase sets the "phase" field.
func (u *DeployTaskUpsertBulk) SetPhase(v deploytask.Phase) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdatePhase() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdatePhase()
	})
}

// ClearPhase clears the value of the "phase" field.
func (u *DeployTaskUpsertBulk) ClearPhase() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearPhase()
	})
}

// SetAttempts sets the "attempts" field.
func (u *DeployTaskUpsertBulk) SetAttempts(v int) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *DeployTaskUpsertBulk) AddAttempts(v int) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateAttempts() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateAttempts()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *DeployTaskUpsertBulk) SetErrorDetail(v string) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateErrorDetail() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateErrorDetail()
	})
}

// ClearErrorDetail clears the value of the "error_detail" field.
func (u *DeployTaskUpsertBulk) ClearErrorDetail() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearErrorDetail()
	})
}

// SetSteps sets the "steps" field.
func (u *DeployTaskUpsertBulk) SetSteps(v []schema.TaskStep) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateSteps() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateSteps()
	})
}

// ClearSteps clears the value of the "steps" field.
func (u *DeployTaskUpsertBulk) ClearSteps() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearSteps()
	})
}

// SetCurrentStep sets the "current_step" field.
func (u *DeployTaskUpsertBulk) SetCurrentStep(v int) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetCurrentStep(v)
	})
}

// AddCurrentStep adds v to the "current_step" field.
func (u *DeployTaskUpsertBulk) AddCurrentStep(v int) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.AddCurrentStep(v)
	})
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateCurrentStep() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateCurrentStep()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *DeployTaskUpsertBulk) SetStartedAt(v time.Time) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateStartedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DeployTaskUpsertBulk) ClearStartedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeployTaskUpsertBulk) SetFinishedAt(v time.Time) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateFinishedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeployTaskUpsertBulk) ClearFinishedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeployTaskUpsertBulk) SetUpdatedAt(v time.Time) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateUpdatedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DeployTaskUpsertBulk) SetDeletedAt(v time.Time) *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DeployTaskUpsertBulk) UpdateDeletedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DeployTaskUpsertBulk) ClearDeletedAt() *DeployTaskUpsertBulk {
	return u.Update(func(s *DeployTaskUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *DeployTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeployTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeployTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeployTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
