// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/director"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/predicate"
	"github.com/th/ngxcp/ent/virtualservice"
)

// DirectorUpdate is the builder for updating Director entities.
type DirectorUpdate struct {
	config
	hooks    []Hook
	mutation *DirectorMutation
}

// Where appends a list predicates to the DirectorUpdate builder.
func (_u *DirectorUpdate) Where(ps ...predicate.Director) *DirectorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *DirectorUpdate) SetState(v director.State) *DirectorUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableState(v *director.State) *DirectorUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *DirectorUpdate) SetPriority(v int) *DirectorUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillablePriority(v *int) *DirectorUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *DirectorUpdate) AddPriority(v int) *DirectorUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetVirtualRouterID sets the "virtual_router_id" field.
func (_u *DirectorUpdate) SetVirtualRouterID(v int) *DirectorUpdate {
	_u.mutation.ResetVirtualRouterID()
	_u.mutation.SetVirtualRouterID(v)
	return _u
}

// SetNillableVirtualRouterID sets the "virtual_router_id" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableVirtualRouterID(v *int) *DirectorUpdate {
	if v != nil {
		_u.SetVirtualRouterID(*v)
	}
	return _u
}

// AddVirtualRouterID adds value to the "virtual_router_id" field.
func (_u *DirectorUpdate) AddVirtualRouterID(v int) *DirectorUpdate {
	_u.mutation.AddVirtualRouterID(v)
	return _u
}

// SetUnicastSrcIP sets the "unicast_src_ip" field.
func (_u *DirectorUpdate) SetUnicastSrcIP(v string) *DirectorUpdate {
	_u.mutation.SetUnicastSrcIP(v)
	return _u
}

// SetNillableUnicastSrcIP sets the "unicast_src_ip" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableUnicastSrcIP(v *string) *DirectorUpdate {
	if v != nil {
		_u.SetUnicastSrcIP(*v)
	}
	return _u
}

// SetUnicastPeerIP sets the "unicast_peer_ip" field.
func (_u *DirectorUpdate) SetUnicastPeerIP(v string) *DirectorUpdate {
	_u.mutation.SetUnicastPeerIP(v)
	return _u
}

// SetNillableUnicastPeerIP sets the "unicast_peer_ip" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableUnicastPeerIP(v *string) *DirectorUpdate {
	if v != nil {
		_u.SetUnicastPeerIP(*v)
	}
	return _u
}

// SetIface sets the "iface" field.
func (_u *DirectorUpdate) SetIface(v string) *DirectorUpdate {
	_u.mutation.SetIface(v)
	return _u
}

// SetNillableIface sets the "iface" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableIface(v *string) *DirectorUpdate {
	if v != nil {
		_u.SetIface(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DirectorUpdate) SetMode(v director.Mode) *DirectorUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableMode(v *director.Mode) *DirectorUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetVip sets the "vip" field.
func (_u *DirectorUpdate) SetVip(v string) *DirectorUpdate {
	_u.mutation.SetVip(v)
	return _u
}

// SetNillableVip sets the "vip" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableVip(v *string) *DirectorUpdate {
	if v != nil {
		_u.SetVip(*v)
	}
	return _u
}

// SetHoldingVip sets the "holding_vip" field.
func (_u *DirectorUpdate) SetHoldingVip(v bool) *DirectorUpdate {
	_u.mutation.SetHoldingVip(v)
	return _u
}

// SetNillableHoldingVip sets the "holding_vip" field if the given value is not nil.
func (_u *DirectorUpdate) SetNillableHoldingVip(v *bool) *DirectorUpdate {
	if v != nil {
		_u.SetHoldingVip(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DirectorUpdate) SetUpdatedAt(v time.Time) *DirectorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *DirectorUpdate) SetNodeID(id int) *DirectorUpdate {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *DirectorUpdate) SetNode(v *Node) *DirectorUpdate {
	return _u.SetNodeID(v.ID)
}

// AddVirtualServiceIDs adds the "virtual_services" edge to the VirtualService entity by IDs.
func (_u *DirectorUpdate) AddVirtualServiceIDs(ids ...int) *DirectorUpdate {
	_u.mutation.AddVirtualServiceIDs(ids...)
	return _u
}

// AddVirtualServices adds the "virtual_services" edges to the VirtualService entity.
func (_u *DirectorUpdate) AddVirtualServices(v ...*VirtualService) *DirectorUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVirtualServiceIDs(ids...)
}

// Mutation returns the DirectorMutation object of the builder.
func (_u *DirectorUpdate) Mutation() *DirectorMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *DirectorUpdate) ClearNode() *DirectorUpdate {
	_u.mutation.ClearNode()
	return _u
}

// ClearVirtualServices clears all "virtual_services" edges to the VirtualService entity.
func (_u *DirectorUpdate) ClearVirtualServices() *DirectorUpdate {
	_u.mutation.ClearVirtualServices()
	return _u
}

// RemoveVirtualServiceIDs removes the "virtual_services" edge to VirtualService entities by IDs.
func (_u *DirectorUpdate) RemoveVirtualServiceIDs(ids ...int) *DirectorUpdate {
	_u.mutation.RemoveVirtualServiceIDs(ids...)
	return _u
}

// RemoveVirtualServices removes "virtual_services" edges to VirtualService entities.
func (_u *DirectorUpdate) RemoveVirtualServices(v ...*VirtualService) *DirectorUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVirtualServiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DirectorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DirectorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DirectorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := director.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectorUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := director.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Director.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := director.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Director.mode": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Director.node"`)
	}
	return nil
}

func (_u *DirectorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(director.Table, director.Columns, sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(director.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(director.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(director.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VirtualRouterID(); ok {
		_spec.SetField(director.FieldVirtualRouterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVirtualRouterID(); ok {
		_spec.AddField(director.FieldVirtualRouterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnicastSrcIP(); ok {
		_spec.SetField(director.FieldUnicastSrcIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnicastPeerIP(); ok {
		_spec.SetField(director.FieldUnicastPeerIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Iface(); ok {
		_spec.SetField(director.FieldIface, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(director.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Vip(); ok {
		_spec.SetField(director.FieldVip, field.TypeString, value)
	}
	if value, ok := _u.mutation.HoldingVip(); ok {
		_spec.SetField(director.FieldHoldingVip, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(director.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   director.NodeTable,
			Columns: []string{director.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   director.NodeTable,
			Columns: []string{director.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VirtualServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVirtualServicesIDs(); len(nodes) > 0 && !_u.mutation.VirtualServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VirtualServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{director.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DirectorUpdateOne is the builder for updating a single Director entity.
type DirectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectorMutation
}

// SetState sets the "state" field.
func (_u *DirectorUpdateOne) SetState(v director.State) *DirectorUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableState(v *director.State) *DirectorUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *DirectorUpdateOne) SetPriority(v int) *DirectorUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillablePriority(v *int) *DirectorUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *DirectorUpdateOne) AddPriority(v int) *DirectorUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetVirtualRouterID sets the "virtual_router_id" field.
func (_u *DirectorUpdateOne) SetVirtualRouterID(v int) *DirectorUpdateOne {
	_u.mutation.ResetVirtualRouterID()
	_u.mutation.SetVirtualRouterID(v)
	return _u
}

// SetNillableVirtualRouterID sets the "virtual_router_id" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableVirtualRouterID(v *int) *DirectorUpdateOne {
	if v != nil {
		_u.SetVirtualRouterID(*v)
	}
	return _u
}

// AddVirtualRouterID adds value to the "virtual_router_id" field.
func (_u *DirectorUpdateOne) AddVirtualRouterID(v int) *DirectorUpdateOne {
	_u.mutation.AddVirtualRouterID(v)
	return _u
}

// SetUnicastSrcIP sets the "unicast_src_ip" field.
func (_u *DirectorUpdateOne) SetUnicastSrcIP(v string) *DirectorUpdateOne {
	_u.mutation.SetUnicastSrcIP(v)
	return _u
}

// SetNillableUnicastSrcIP sets the "unicast_src_ip" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableUnicastSrcIP(v *string) *DirectorUpdateOne {
	if v != nil {
		_u.SetUnicastSrcIP(*v)
	}
	return _u
}

// SetUnicastPeerIP sets the "unicast_peer_ip" field.
func (_u *DirectorUpdateOne) SetUnicastPeerIP(v string) *DirectorUpdateOne {
	_u.mutation.SetUnicastPeerIP(v)
	return _u
}

// SetNillableUnicastPeerIP sets the "unicast_peer_ip" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableUnicastPeerIP(v *string) *DirectorUpdateOne {
	if v != nil {
		_u.SetUnicastPeerIP(*v)
	}
	return _u
}

// SetIface sets the "iface" field.
func (_u *DirectorUpdateOne) SetIface(v string) *DirectorUpdateOne {
	_u.mutation.SetIface(v)
	return _u
}

// SetNillableIface sets the "iface" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableIface(v *string) *DirectorUpdateOne {
	if v != nil {
		_u.SetIface(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DirectorUpdateOne) SetMode(v director.Mode) *DirectorUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableMode(v *director.Mode) *DirectorUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetVip sets the "vip" field.
func (_u *DirectorUpdateOne) SetVip(v string) *DirectorUpdateOne {
	_u.mutation.SetVip(v)
	return _u
}

// SetNillableVip sets the "vip" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableVip(v *string) *DirectorUpdateOne {
	if v != nil {
		_u.SetVip(*v)
	}
	return _u
}

// SetHoldingVip sets the "holding_vip" field.
func (_u *DirectorUpdateOne) SetHoldingVip(v bool) *DirectorUpdateOne {
	_u.mutation.SetHoldingVip(v)
	return _u
}

// SetNillableHoldingVip sets the "holding_vip" field if the given value is not nil.
func (_u *DirectorUpdateOne) SetNillableHoldingVip(v *bool) *DirectorUpdateOne {
	if v != nil {
		_u.SetHoldingVip(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DirectorUpdateOne) SetUpdatedAt(v time.Time) *DirectorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *DirectorUpdateOne) SetNodeID(id int) *DirectorUpdateOne {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *DirectorUpdateOne) SetNode(v *Node) *DirectorUpdateOne {
	return _u.SetNodeID(v.ID)
}

// AddVirtualServiceIDs adds the "virtual_services" edge to the VirtualService entity by IDs.
func (_u *DirectorUpdateOne) AddVirtualServiceIDs(ids ...int) *DirectorUpdateOne {
	_u.mutation.AddVirtualServiceIDs(ids...)
	return _u
}

// AddVirtualServices adds the "virtual_services" edges to the VirtualService entity.
func (_u *DirectorUpdateOne) AddVirtualServices(v ...*VirtualService) *DirectorUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVirtualServiceIDs(ids...)
}

// Mutation returns the DirectorMutation object of the builder.
func (_u *DirectorUpdateOne) Mutation() *DirectorMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *DirectorUpdateOne) ClearNode() *DirectorUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// ClearVirtualServices clears all "virtual_services" edges to the VirtualService entity.
func (_u *DirectorUpdateOne) ClearVirtualServices() *DirectorUpdateOne {
	_u.mutation.ClearVirtualServices()
	return _u
}

// RemoveVirtualServiceIDs removes the "virtual_services" edge to VirtualService entities by IDs.
func (_u *DirectorUpdateOne) RemoveVirtualServiceIDs(ids ...int) *DirectorUpdateOne {
	_u.mutation.RemoveVirtualServiceIDs(ids...)
	return _u
}

// RemoveVirtualServices removes "virtual_services" edges to VirtualService entities.
func (_u *DirectorUpdateOne) RemoveVirtualServices(v ...*VirtualService) *DirectorUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVirtualServiceIDs(ids...)
}

// Where appends a list predicates to the DirectorUpdate builder.
func (_u *DirectorUpdateOne) Where(ps ...predicate.Director) *DirectorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DirectorUpdateOne) Select(field string, fields ...string) *DirectorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Director entity.
func (_u *DirectorUpdateOne) Save(ctx context.Context) (*Director, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectorUpdateOne) SaveX(ctx context.Context) *Director {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DirectorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DirectorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := director.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectorUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := director.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Director.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := director.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Director.mode": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Director.node"`)
	}
	return nil
}

func (_u *DirectorUpdateOne) sqlSave(ctx context.Context) (_node *Director, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(director.Table, director.Columns, sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Director.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, director.FieldID)
		for _, f := range fields {
			if !director.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != director.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(director.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(director.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(director.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VirtualRouterID(); ok {
		_spec.SetField(director.FieldVirtualRouterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVirtualRouterID(); ok {
		_spec.AddField(director.FieldVirtualRouterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnicastSrcIP(); ok {
		_spec.SetField(director.FieldUnicastSrcIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnicastPeerIP(); ok {
		_spec.SetField(director.FieldUnicastPeerIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Iface(); ok {
		_spec.SetField(director.FieldIface, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(director.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Vip(); ok {
		_spec.SetField(director.FieldVip, field.TypeString, value)
	}
	if value, ok := _u.mutation.HoldingVip(); ok {
		_spec.SetField(director.FieldHoldingVip, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(director.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   director.NodeTable,
			Columns: []string{director.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   director.NodeTable,
			Columns: []string{director.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VirtualServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVirtualServicesIDs(); len(nodes) > 0 && !_u.mutation.VirtualServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VirtualServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.VirtualServicesTable,
			Columns: []string{director.VirtualServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualservice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Director{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{director.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
