// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/enrolltoken"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/predicate"
)

// EnrollTokenUpdate is the builder for updating EnrollToken entities.
type EnrollTokenUpdate struct {
	config
	hooks    []Hook
	mutation *EnrollTokenMutation
}

// Where appends a list predicates to the EnrollTokenUpdate builder.
func (_u *EnrollTokenUpdate) Where(ps ...predicate.EnrollToken) *EnrollTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *EnrollTokenUpdate) SetTokenHash(v string) *EnrollTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *EnrollTokenUpdate) SetNillableTokenHash(v *string) *EnrollTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnrollTokenUpdate) SetExpiresAt(v time.Time) *EnrollTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnrollTokenUpdate) SetNillableExpiresAt(v *time.Time) *EnrollTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *EnrollTokenUpdate) SetUsed(v bool) *EnrollTokenUpdate {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *EnrollTokenUpdate) SetNillableUsed(v *bool) *EnrollTokenUpdate {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *EnrollTokenUpdate) SetRevoked(v bool) *EnrollTokenUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *EnrollTokenUpdate) SetNillableRevoked(v *bool) *EnrollTokenUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *EnrollTokenUpdate) SetUsedAt(v time.Time) *EnrollTokenUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *EnrollTokenUpdate) SetNillableUsedAt(v *time.Time) *EnrollTokenUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *EnrollTokenUpdate) ClearUsedAt() *EnrollTokenUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnrollTokenUpdate) SetUpdatedAt(v time.Time) *EnrollTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *EnrollTokenUpdate) SetNodeID(id int) *EnrollTokenUpdate {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *EnrollTokenUpdate) SetNode(v *Node) *EnrollTokenUpdate {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the EnrollTokenMutation object of the builder.
func (_u *EnrollTokenUpdate) Mutation() *EnrollTokenMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *EnrollTokenUpdate) ClearNode() *EnrollTokenUpdate {
	_u.mutation.ClearNode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnrollTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnrollTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnrollTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enrolltoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollTokenUpdate) check() error {
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnrollToken.node"`)
	}
	return nil
}

func (_u *EnrollTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrolltoken.Table, enrolltoken.Columns, sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(enrolltoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enrolltoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(enrolltoken.FieldUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(enrolltoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(enrolltoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(enrolltoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enrolltoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrolltoken.NodeTable,
			Columns: []string{enrolltoken.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrolltoken.NodeTable,
			Columns: []string{enrolltoken.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrolltoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnrollTokenUpdateOne is the builder for updating a single EnrollToken entity.
type EnrollTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnrollTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *EnrollTokenUpdateOne) SetTokenHash(v string) *EnrollTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *EnrollTokenUpdateOne) SetNillableTokenHash(v *string) *EnrollTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnrollTokenUpdateOne) SetExpiresAt(v time.Time) *EnrollTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnrollTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *EnrollTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsed sets the "used" field.
func (_u *EnrollTokenUpdateOne) SetUsed(v bool) *EnrollTokenUpdateOne {
	_u.mutation.SetUsed(v)
	return _u
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_u *EnrollTokenUpdateOne) SetNillableUsed(v *bool) *EnrollTokenUpdateOne {
	if v != nil {
		_u.SetUsed(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *EnrollTokenUpdateOne) SetRevoked(v bool) *EnrollTokenUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *EnrollTokenUpdateOne) SetNillableRevoked(v *bool) *EnrollTokenUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *EnrollTokenUpdateOne) SetUsedAt(v time.Time) *EnrollTokenUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *EnrollTokenUpdateOne) SetNillableUsedAt(v *time.Time) *EnrollTokenUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *EnrollTokenUpdateOne) ClearUsedAt() *EnrollTokenUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnrollTokenUpdateOne) SetUpdatedAt(v time.Time) *EnrollTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_u *EnrollTokenUpdateOne) SetNodeID(id int) *EnrollTokenUpdateOne {
	_u.mutation.SetNodeID(id)
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *EnrollTokenUpdateOne) SetNode(v *Node) *EnrollTokenUpdateOne {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the EnrollTokenMutation object of the builder.
func (_u *EnrollTokenUpdateOne) Mutation() *EnrollTokenMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *EnrollTokenUpdateOne) ClearNode() *EnrollTokenUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// Where appends a list predicates to the EnrollTokenUpdate builder.
func (_u *EnrollTokenUpdateOne) Where(ps ...predicate.EnrollToken) *EnrollTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnrollTokenUpdateOne) Select(field string, fields ...string) *EnrollTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnrollToken entity.
func (_u *EnrollTokenUpdateOne) Save(ctx context.Context) (*EnrollToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollTokenUpdateOne) SaveX(ctx context.Context) *EnrollToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnrollTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnrollTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enrolltoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollTokenUpdateOne) check() error {
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnrollToken.node"`)
	}
	return nil
}

func (_u *EnrollTokenUpdateOne) sqlSave(ctx context.Context) (_node *EnrollToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrolltoken.Table, enrolltoken.Columns, sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnrollToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enrolltoken.FieldID)
		for _, f := range fields {
			if !enrolltoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enrolltoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(enrolltoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enrolltoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Used(); ok {
		_spec.SetField(enrolltoken.FieldUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(enrolltoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(enrolltoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(enrolltoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enrolltoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrolltoken.NodeTable,
			Columns: []string{enrolltoken.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrolltoken.NodeTable,
			Columns: []string{enrolltoken.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnrollToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrolltoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
