// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/jointoken"
	"github.com/th/ngxcp/ent/predicate"
)

// JoinTokenDelete is the builder for deleting a JoinToken entity.
type JoinTokenDelete struct {
	config
	hooks    []Hook
	mutation *JoinTokenMutation
}

// Where appends a list predicates to the JoinTokenDelete builder.
func (_d *JoinTokenDelete) Where(ps ...predicate.JoinToken) *JoinTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *JoinTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JoinTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *JoinTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jointoken.Table, sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// JoinTokenDeleteOne is the builder for deleting a single JoinToken entity.
type JoinTokenDeleteOne struct {
	_d *JoinTokenDelete
}

// Where appends a list predicates to the JoinTokenDelete builder.
func (_d *JoinTokenDeleteOne) Where(ps ...predicate.JoinToken) *JoinTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *JoinTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jointoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JoinTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
