// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/nodecapability"
	"github.com/th/ngxcp/ent/predicate"
)

// NodeCapabilityDelete is the builder for deleting a NodeCapability entity.
type NodeCapabilityDelete struct {
	config
	hooks    []Hook
	mutation *NodeCapabilityMutation
}

// Where appends a list predicates to the NodeCapabilityDelete builder.
func (_d *NodeCapabilityDelete) Where(ps ...predicate.NodeCapability) *NodeCapabilityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NodeCapabilityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeCapabilityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NodeCapabilityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nodecapability.Table, sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NodeCapabilityDeleteOne is the builder for deleting a single NodeCapability entity.
type NodeCapabilityDeleteOne struct {
	_d *NodeCapabilityDelete
}

// Where appends a list predicates to the NodeCapabilityDelete builder.
func (_d *NodeCapabilityDeleteOne) Where(ps ...predicate.NodeCapability) *NodeCapabilityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NodeCapabilityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nodecapability.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeCapabilityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
