// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/nodeconfigfile"
)

// NodeConfigFile is the model entity for the NodeConfigFile schema.
type NodeConfigFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// ModTime holds the value of the "mod_time" field.
	ModTime time.Time `json:"mod_time,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt time.Time `json:"captured_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeConfigFileQuery when eager-loading is set.
	Edges             NodeConfigFileEdges `json:"edges"`
	node_config_files *int
	selectValues      sql.SelectValues
}

// NodeConfigFileEdges holds the relations/edges for other nodes in the graph.
type NodeConfigFileEdges struct {
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeConfigFileEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeConfigFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeconfigfile.FieldID, nodeconfigfile.FieldSize:
			values[i] = new(sql.NullInt64)
		case nodeconfigfile.FieldPath, nodeconfigfile.FieldSha256:
			values[i] = new(sql.NullString)
		case nodeconfigfile.FieldModTime, nodeconfigfile.FieldCapturedAt, nodeconfigfile.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case nodeconfigfile.ForeignKeys[0]: // node_config_files
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeConfigFile fields.
func (_m *NodeConfigFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeconfigfile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case nodeconfigfile.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case nodeconfigfile.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case nodeconfigfile.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case nodeconfigfile.FieldModTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field mod_time", values[i])
			} else if value.Valid {
				_m.ModTime = value.Time
			}
		case nodeconfigfile.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				_m.CapturedAt = value.Time
			}
		case nodeconfigfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nodeconfigfile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field node_config_files", value)
			} else if value.Valid {
				_m.node_config_files = new(int)
				*_m.node_config_files = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeConfigFile.
// This includes values selected through modifiers, order, etc.
func (_m *NodeConfigFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNode queries the "node" edge of the NodeConfigFile entity.
func (_m *NodeConfigFile) QueryNode() *NodeQuery {
	return NewNodeConfigFileClient(_m.config).QueryNode(_m)
}

// Update returns a builder for updating this NodeConfigFile.
// Note that you need to call NodeConfigFile.Unwrap() before calling this method if this NodeConfigFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeConfigFile) Update() *NodeConfigFileUpdateOne {
	return NewNodeConfigFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeConfigFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeConfigFile) Unwrap() *NodeConfigFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeConfigFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeConfigFile) String() string {
	var builder strings.Builder
	builder.WriteString("NodeConfigFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("mod_time=")
	builder.WriteString(_m.ModTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("captured_at=")
	builder.WriteString(_m.CapturedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NodeConfigFiles is a parsable slice of NodeConfigFile.
type NodeConfigFiles []*NodeConfigFile
