// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/cluster"
	"github.com/th/ngxcp/ent/configsnapshot"
	"github.com/th/ngxcp/ent/deploytask"
	"github.com/th/ngxcp/ent/director"
	"github.com/th/ngxcp/ent/enrolltoken"
	"github.com/th/ngxcp/ent/jointoken"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/nodecapability"
	"github.com/th/ngxcp/ent/nodeconfigfile"
	"github.com/th/ngxcp/ent/nodelogtarget"
	"github.com/th/ngxcp/ent/predicate"
	"github.com/th/ngxcp/ent/realserver"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdate) SetName(v string) *NodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableName(v *string) *NodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *NodeUpdate) SetAddress(v string) *NodeUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableAddress(v *string) *NodeUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *NodeUpdate) SetRole(v node.Role) *NodeUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableRole(v *node.Role) *NodeUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdate) SetStatus(v node.Status) *NodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableStatus(v *node.Status) *NodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLvsWeight sets the "lvs_weight" field.
func (_u *NodeUpdate) SetLvsWeight(v int) *NodeUpdate {
	_u.mutation.ResetLvsWeight()
	_u.mutation.SetLvsWeight(v)
	return _u
}

// SetNillableLvsWeight sets the "lvs_weight" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLvsWeight(v *int) *NodeUpdate {
	if v != nil {
		_u.SetLvsWeight(*v)
	}
	return _u
}

// AddLvsWeight adds value to the "lvs_weight" field.
func (_u *NodeUpdate) AddLvsWeight(v int) *NodeUpdate {
	_u.mutation.AddLvsWeight(v)
	return _u
}

// SetLvsEnabled sets the "lvs_enabled" field.
func (_u *NodeUpdate) SetLvsEnabled(v bool) *NodeUpdate {
	_u.mutation.SetLvsEnabled(v)
	return _u
}

// SetNillableLvsEnabled sets the "lvs_enabled" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLvsEnabled(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetLvsEnabled(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *NodeUpdate) SetLastHeartbeatAt(v time.Time) *NodeUpdate {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastHeartbeatAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *NodeUpdate) ClearLastHeartbeatAt() *NodeUpdate {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NodeUpdate) SetDeletedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableDeletedAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NodeUpdate) ClearDeletedAt() *NodeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddCapabilityIDs adds the "capabilities" edge to the NodeCapability entity by IDs.
func (_u *NodeUpdate) AddCapabilityIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddCapabilityIDs(ids...)
	return _u
}

// AddCapabilities adds the "capabilities" edges to the NodeCapability entity.
func (_u *NodeUpdate) AddCapabilities(v ...*NodeCapability) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCapabilityIDs(ids...)
}

// AddConfigFileIDs adds the "config_files" edge to the NodeConfigFile entity by IDs.
func (_u *NodeUpdate) AddConfigFileIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddConfigFileIDs(ids...)
	return _u
}

// AddConfigFiles adds the "config_files" edges to the NodeConfigFile entity.
func (_u *NodeUpdate) AddConfigFiles(v ...*NodeConfigFile) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigFileIDs(ids...)
}

// AddLogTargetIDs adds the "log_targets" edge to the NodeLogTarget entity by IDs.
func (_u *NodeUpdate) AddLogTargetIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddLogTargetIDs(ids...)
	return _u
}

// AddLogTargets adds the "log_targets" edges to the NodeLogTarget entity.
func (_u *NodeUpdate) AddLogTargets(v ...*NodeLogTarget) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogTargetIDs(ids...)
}

// AddSnapshotIDs adds the "snapshots" edge to the ConfigSnapshot entity by IDs.
func (_u *NodeUpdate) AddSnapshotIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the ConfigSnapshot entity.
func (_u *NodeUpdate) AddSnapshots(v ...*ConfigSnapshot) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddDeployTaskIDs adds the "deploy_tasks" edge to the DeployTask entity by IDs.
func (_u *NodeUpdate) AddDeployTaskIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddDeployTaskIDs(ids...)
	return _u
}

// AddDeployTasks adds the "deploy_tasks" edges to the DeployTask entity.
func (_u *NodeUpdate) AddDeployTasks(v ...*DeployTask) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTaskIDs(ids...)
}

// AddRealServerIDs adds the "real_servers" edge to the RealServer entity by IDs.
func (_u *NodeUpdate) AddRealServerIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddRealServerIDs(ids...)
	return _u
}

// AddRealServers adds the "real_servers" edges to the RealServer entity.
func (_u *NodeUpdate) AddRealServers(v ...*RealServer) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRealServerIDs(ids...)
}

// AddJoinTokenIDs adds the "join_tokens" edge to the JoinToken entity by IDs.
func (_u *NodeUpdate) AddJoinTokenIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddJoinTokenIDs(ids...)
	return _u
}

// AddJoinTokens adds the "join_tokens" edges to the JoinToken entity.
func (_u *NodeUpdate) AddJoinTokens(v ...*JoinToken) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJoinTokenIDs(ids...)
}

// AddEnrollTokenIDs adds the "enroll_tokens" edge to the EnrollToken entity by IDs.
func (_u *NodeUpdate) AddEnrollTokenIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddEnrollTokenIDs(ids...)
	return _u
}

// AddEnrollTokens adds the "enroll_tokens" edges to the EnrollToken entity.
func (_u *NodeUpdate) AddEnrollTokens(v ...*EnrollToken) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollTokenIDs(ids...)
}

// AddDirectorIDs adds the "directors" edge to the Director entity by IDs.
func (_u *NodeUpdate) AddDirectorIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddDirectorIDs(ids...)
	return _u
}

// AddDirectors adds the "directors" edges to the Director entity.
func (_u *NodeUpdate) AddDirectors(v ...*Director) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDirectorIDs(ids...)
}

// SetClusterID sets the "cluster" edge to the Cluster entity by ID.
func (_u *NodeUpdate) SetClusterID(id int) *NodeUpdate {
	_u.mutation.SetClusterID(id)
	return _u
}

// SetNillableClusterID sets the "cluster" edge to the Cluster entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillableClusterID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetClusterID(*id)
	}
	return _u
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_u *NodeUpdate) SetCluster(v *Cluster) *NodeUpdate {
	return _u.SetClusterID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearCapabilities clears all "capabilities" edges to the NodeCapability entity.
func (_u *NodeUpdate) ClearCapabilities() *NodeUpdate {
	_u.mutation.ClearCapabilities()
	return _u
}

// RemoveCapabilityIDs removes the "capabilities" edge to NodeCapability entities by IDs.
func (_u *NodeUpdate) RemoveCapabilityIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveCapabilityIDs(ids...)
	return _u
}

// RemoveCapabilities removes "capabilities" edges to NodeCapability entities.
func (_u *NodeUpdate) RemoveCapabilities(v ...*NodeCapability) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCapabilityIDs(ids...)
}

// ClearConfigFiles clears all "config_files" edges to the NodeConfigFile entity.
func (_u *NodeUpdate) ClearConfigFiles() *NodeUpdate {
	_u.mutation.ClearConfigFiles()
	return _u
}

// RemoveConfigFileIDs removes the "config_files" edge to NodeConfigFile entities by IDs.
func (_u *NodeUpdate) RemoveConfigFileIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveConfigFileIDs(ids...)
	return _u
}

// RemoveConfigFiles removes "config_files" edges to NodeConfigFile entities.
func (_u *NodeUpdate) RemoveConfigFiles(v ...*NodeConfigFile) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigFileIDs(ids...)
}

// ClearLogTargets clears all "log_targets" edges to the NodeLogTarget entity.
func (_u *NodeUpdate) ClearLogTargets() *NodeUpdate {
	_u.mutation.ClearLogTargets()
	return _u
}

// RemoveLogTargetIDs removes the "log_targets" edge to NodeLogTarget entities by IDs.
func (_u *NodeUpdate) RemoveLogTargetIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveLogTargetIDs(ids...)
	return _u
}

// RemoveLogTargets removes "log_targets" edges to NodeLogTarget entities.
func (_u *NodeUpdate) RemoveLogTargets(v ...*NodeLogTarget) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogTargetIDs(ids...)
}

// ClearSnapshots clears all "snapshots" edges to the ConfigSnapshot entity.
func (_u *NodeUpdate) ClearSnapshots() *NodeUpdate {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to ConfigSnapshot entities by IDs.
func (_u *NodeUpdate) RemoveSnapshotIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to ConfigSnapshot entities.
func (_u *NodeUpdate) RemoveSnapshots(v ...*ConfigSnapshot) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearDeployTasks clears all "deploy_tasks" edges to the DeployTask entity.
func (_u *NodeUpdate) ClearDeployTasks() *NodeUpdate {
	_u.mutation.ClearDeployTasks()
	return _u
}

// RemoveDeployTaskIDs removes the "deploy_tasks" edge to DeployTask entities by IDs.
func (_u *NodeUpdate) RemoveDeployTaskIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveDeployTaskIDs(ids...)
	return _u
}

// RemoveDeployTasks removes "deploy_tasks" edges to DeployTask entities.
func (_u *NodeUpdate) RemoveDeployTasks(v ...*DeployTask) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTaskIDs(ids...)
}

// ClearRealServers clears all "real_servers" edges to the RealServer entity.
func (_u *NodeUpdate) ClearRealServers() *NodeUpdate {
	_u.mutation.ClearRealServers()
	return _u
}

// RemoveRealServerIDs removes the "real_servers" edge to RealServer entities by IDs.
func (_u *NodeUpdate) RemoveRealServerIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveRealServerIDs(ids...)
	return _u
}

// RemoveRealServers removes "real_servers" edges to RealServer entities.
func (_u *NodeUpdate) RemoveRealServers(v ...*RealServer) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRealServerIDs(ids...)
}

// ClearJoinTokens clears all "join_tokens" edges to the JoinToken entity.
func (_u *NodeUpdate) ClearJoinTokens() *NodeUpdate {
	_u.mutation.ClearJoinTokens()
	return _u
}

// RemoveJoinTokenIDs removes the "join_tokens" edge to JoinToken entities by IDs.
func (_u *NodeUpdate) RemoveJoinTokenIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveJoinTokenIDs(ids...)
	return _u
}

// RemoveJoinTokens removes "join_tokens" edges to JoinToken entities.
func (_u *NodeUpdate) RemoveJoinTokens(v ...*JoinToken) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJoinTokenIDs(ids...)
}

// ClearEnrollTokens clears all "enroll_tokens" edges to the EnrollToken entity.
func (_u *NodeUpdate) ClearEnrollTokens() *NodeUpdate {
	_u.mutation.ClearEnrollTokens()
	return _u
}

// RemoveEnrollTokenIDs removes the "enroll_tokens" edge to EnrollToken entities by IDs.
func (_u *NodeUpdate) RemoveEnrollTokenIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveEnrollTokenIDs(ids...)
	return _u
}

// RemoveEnrollTokens removes "enroll_tokens" edges to EnrollToken entities.
func (_u *NodeUpdate) RemoveEnrollTokens(v ...*EnrollToken) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollTokenIDs(ids...)
}

// ClearDirectors clears all "directors" edges to the Director entity.
func (_u *NodeUpdate) ClearDirectors() *NodeUpdate {
	_u.mutation.ClearDirectors()
	return _u
}

// RemoveDirectorIDs removes the "directors" edge to Director entities by IDs.
func (_u *NodeUpdate) RemoveDirectorIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveDirectorIDs(ids...)
	return _u
}

// RemoveDirectors removes "directors" edges to Director entities.
func (_u *NodeUpdate) RemoveDirectors(v ...*Director) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDirectorIDs(ids...)
}

// ClearCluster clears the "cluster" edge to the Cluster entity.
func (_u *NodeUpdate) ClearCluster() *NodeUpdate {
	_u.mutation.ClearCluster()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := node.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Node.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := node.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Node.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(node.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(node.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LvsWeight(); ok {
		_spec.SetField(node.FieldLvsWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLvsWeight(); ok {
		_spec.AddField(node.FieldLvsWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LvsEnabled(); ok {
		_spec.SetField(node.FieldLvsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(node.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(node.FieldLastHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(node.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(node.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.CapabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCapabilitiesIDs(); len(nodes) > 0 && !_u.mutation.CapabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigFilesIDs(); len(nodes) > 0 && !_u.mutation.ConfigFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogTargetsIDs(); len(nodes) > 0 && !_u.mutation.LogTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTasksIDs(); len(nodes) > 0 && !_u.mutation.DeployTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RealServersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRealServersIDs(); len(nodes) > 0 && !_u.mutation.RealServersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealServersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JoinTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJoinTokensIDs(); len(nodes) > 0 && !_u.mutation.JoinTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JoinTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollTokensIDs(); len(nodes) > 0 && !_u.mutation.EnrollTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDirectorsIDs(); len(nodes) > 0 && !_u.mutation.DirectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClusterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ClusterTable,
			Columns: []string{node.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ClusterTable,
			Columns: []string{node.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetName sets the "name" field.
func (_u *NodeUpdateOne) SetName(v string) *NodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableName(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *NodeUpdateOne) SetAddress(v string) *NodeUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableAddress(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *NodeUpdateOne) SetRole(v node.Role) *NodeUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableRole(v *node.Role) *NodeUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdateOne) SetStatus(v node.Status) *NodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableStatus(v *node.Status) *NodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLvsWeight sets the "lvs_weight" field.
func (_u *NodeUpdateOne) SetLvsWeight(v int) *NodeUpdateOne {
	_u.mutation.ResetLvsWeight()
	_u.mutation.SetLvsWeight(v)
	return _u
}

// SetNillableLvsWeight sets the "lvs_weight" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLvsWeight(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetLvsWeight(*v)
	}
	return _u
}

// AddLvsWeight adds value to the "lvs_weight" field.
func (_u *NodeUpdateOne) AddLvsWeight(v int) *NodeUpdateOne {
	_u.mutation.AddLvsWeight(v)
	return _u
}

// SetLvsEnabled sets the "lvs_enabled" field.
func (_u *NodeUpdateOne) SetLvsEnabled(v bool) *NodeUpdateOne {
	_u.mutation.SetLvsEnabled(v)
	return _u
}

// SetNillableLvsEnabled sets the "lvs_enabled" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLvsEnabled(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetLvsEnabled(*v)
	}
	return _u
}

// SetLastHeartbeatAt sets the "last_heartbeat_at" field.
func (_u *NodeUpdateOne) SetLastHeartbeatAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetLastHeartbeatAt(v)
	return _u
}

// SetNillableLastHeartbeatAt sets the "last_heartbeat_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastHeartbeatAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetLastHeartbeatAt(*v)
	}
	return _u
}

// ClearLastHeartbeatAt clears the value of the "last_heartbeat_at" field.
func (_u *NodeUpdateOne) ClearLastHeartbeatAt() *NodeUpdateOne {
	_u.mutation.ClearLastHeartbeatAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NodeUpdateOne) SetDeletedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableDeletedAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NodeUpdateOne) ClearDeletedAt() *NodeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddCapabilityIDs adds the "capabilities" edge to the NodeCapability entity by IDs.
func (_u *NodeUpdateOne) AddCapabilityIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddCapabilityIDs(ids...)
	return _u
}

// AddCapabilities adds the "capabilities" edges to the NodeCapability entity.
func (_u *NodeUpdateOne) AddCapabilities(v ...*NodeCapability) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCapabilityIDs(ids...)
}

// AddConfigFileIDs adds the "config_files" edge to the NodeConfigFile entity by IDs.
func (_u *NodeUpdateOne) AddConfigFileIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddConfigFileIDs(ids...)
	return _u
}

// AddConfigFiles adds the "config_files" edges to the NodeConfigFile entity.
func (_u *NodeUpdateOne) AddConfigFiles(v ...*NodeConfigFile) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigFileIDs(ids...)
}

// AddLogTargetIDs adds the "log_targets" edge to the NodeLogTarget entity by IDs.
func (_u *NodeUpdateOne) AddLogTargetIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddLogTargetIDs(ids...)
	return _u
}

// AddLogTargets adds the "log_targets" edges to the NodeLogTarget entity.
func (_u *NodeUpdateOne) AddLogTargets(v ...*NodeLogTarget) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogTargetIDs(ids...)
}

// AddSnapshotIDs adds the "snapshots" edge to the ConfigSnapshot entity by IDs.
func (_u *NodeUpdateOne) AddSnapshotIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the ConfigSnapshot entity.
func (_u *NodeUpdateOne) AddSnapshots(v ...*ConfigSnapshot) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddDeployTaskIDs adds the "deploy_tasks" edge to the DeployTask entity by IDs.
func (_u *NodeUpdateOne) AddDeployTaskIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddDeployTaskIDs(ids...)
	return _u
}

// AddDeployTasks adds the "deploy_tasks" edges to the DeployTask entity.
func (_u *NodeUpdateOne) AddDeployTasks(v ...*DeployTask) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTaskIDs(ids...)
}

// AddRealServerIDs adds the "real_servers" edge to the RealServer entity by IDs.
func (_u *NodeUpdateOne) AddRealServerIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddRealServerIDs(ids...)
	return _u
}

// AddRealServers adds the "real_servers" edges to the RealServer entity.
func (_u *NodeUpdateOne) AddRealServers(v ...*RealServer) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRealServerIDs(ids...)
}

// AddJoinTokenIDs adds the "join_tokens" edge to the JoinToken entity by IDs.
func (_u *NodeUpdateOne) AddJoinTokenIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddJoinTokenIDs(ids...)
	return _u
}

// AddJoinTokens adds the "join_tokens" edges to the JoinToken entity.
func (_u *NodeUpdateOne) AddJoinTokens(v ...*JoinToken) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJoinTokenIDs(ids...)
}

// AddEnrollTokenIDs adds the "enroll_tokens" edge to the EnrollToken entity by IDs.
func (_u *NodeUpdateOne) AddEnrollTokenIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddEnrollTokenIDs(ids...)
	return _u
}

// AddEnrollTokens adds the "enroll_tokens" edges to the EnrollToken entity.
func (_u *NodeUpdateOne) AddEnrollTokens(v ...*EnrollToken) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollTokenIDs(ids...)
}

// AddDirectorIDs adds the "directors" edge to the Director entity by IDs.
func (_u *NodeUpdateOne) AddDirectorIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddDirectorIDs(ids...)
	return _u
}

// AddDirectors adds the "directors" edges to the Director entity.
func (_u *NodeUpdateOne) AddDirectors(v ...*Director) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDirectorIDs(ids...)
}

// SetClusterID sets the "cluster" edge to the Cluster entity by ID.
func (_u *NodeUpdateOne) SetClusterID(id int) *NodeUpdateOne {
	_u.mutation.SetClusterID(id)
	return _u
}

// SetNillableClusterID sets the "cluster" edge to the Cluster entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableClusterID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetClusterID(*id)
	}
	return _u
}

// SetCluster sets the "cluster" edge to the Cluster entity.
func (_u *NodeUpdateOne) SetCluster(v *Cluster) *NodeUpdateOne {
	return _u.SetClusterID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearCapabilities clears all "capabilities" edges to the NodeCapability entity.
func (_u *NodeUpdateOne) ClearCapabilities() *NodeUpdateOne {
	_u.mutation.ClearCapabilities()
	return _u
}

// RemoveCapabilityIDs removes the "capabilities" edge to NodeCapability entities by IDs.
func (_u *NodeUpdateOne) RemoveCapabilityIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveCapabilityIDs(ids...)
	return _u
}

// RemoveCapabilities removes "capabilities" edges to NodeCapability entities.
func (_u *NodeUpdateOne) RemoveCapabilities(v ...*NodeCapability) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCapabilityIDs(ids...)
}

// ClearConfigFiles clears all "config_files" edges to the NodeConfigFile entity.
func (_u *NodeUpdateOne) ClearConfigFiles() *NodeUpdateOne {
	_u.mutation.ClearConfigFiles()
	return _u
}

// RemoveConfigFileIDs removes the "config_files" edge to NodeConfigFile entities by IDs.
func (_u *NodeUpdateOne) RemoveConfigFileIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveConfigFileIDs(ids...)
	return _u
}

// RemoveConfigFiles removes "config_files" edges to NodeConfigFile entities.
func (_u *NodeUpdateOne) RemoveConfigFiles(v ...*NodeConfigFile) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigFileIDs(ids...)
}

// ClearLogTargets clears all "log_targets" edges to the NodeLogTarget entity.
func (_u *NodeUpdateOne) ClearLogTargets() *NodeUpdateOne {
	_u.mutation.ClearLogTargets()
	return _u
}

// RemoveLogTargetIDs removes the "log_targets" edge to NodeLogTarget entities by IDs.
func (_u *NodeUpdateOne) RemoveLogTargetIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveLogTargetIDs(ids...)
	return _u
}

// RemoveLogTargets removes "log_targets" edges to NodeLogTarget entities.
func (_u *NodeUpdateOne) RemoveLogTargets(v ...*NodeLogTarget) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogTargetIDs(ids...)
}

// ClearSnapshots clears all "snapshots" edges to the ConfigSnapshot entity.
func (_u *NodeUpdateOne) ClearSnapshots() *NodeUpdateOne {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to ConfigSnapshot entities by IDs.
func (_u *NodeUpdateOne) RemoveSnapshotIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to ConfigSnapshot entities.
func (_u *NodeUpdateOne) RemoveSnapshots(v ...*ConfigSnapshot) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearDeployTasks clears all "deploy_tasks" edges to the DeployTask entity.
func (_u *NodeUpdateOne) ClearDeployTasks() *NodeUpdateOne {
	_u.mutation.ClearDeployTasks()
	return _u
}

// RemoveDeployTaskIDs removes the "deploy_tasks" edge to DeployTask entities by IDs.
func (_u *NodeUpdateOne) RemoveDeployTaskIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveDeployTaskIDs(ids...)
	return _u
}

// RemoveDeployTasks removes "deploy_tasks" edges to DeployTask entities.
func (_u *NodeUpdateOne) RemoveDeployTasks(v ...*DeployTask) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTaskIDs(ids...)
}

// ClearRealServers clears all "real_servers" edges to the RealServer entity.
func (_u *NodeUpdateOne) ClearRealServers() *NodeUpdateOne {
	_u.mutation.ClearRealServers()
	return _u
}

// RemoveRealServerIDs removes the "real_servers" edge to RealServer entities by IDs.
func (_u *NodeUpdateOne) RemoveRealServerIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveRealServerIDs(ids...)
	return _u
}

// RemoveRealServers removes "real_servers" edges to RealServer entities.
func (_u *NodeUpdateOne) RemoveRealServers(v ...*RealServer) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRealServerIDs(ids...)
}

// ClearJoinTokens clears all "join_tokens" edges to the JoinToken entity.
func (_u *NodeUpdateOne) ClearJoinTokens() *NodeUpdateOne {
	_u.mutation.ClearJoinTokens()
	return _u
}

// RemoveJoinTokenIDs removes the "join_tokens" edge to JoinToken entities by IDs.
func (_u *NodeUpdateOne) RemoveJoinTokenIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveJoinTokenIDs(ids...)
	return _u
}

// RemoveJoinTokens removes "join_tokens" edges to JoinToken entities.
func (_u *NodeUpdateOne) RemoveJoinTokens(v ...*JoinToken) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJoinTokenIDs(ids...)
}

// ClearEnrollTokens clears all "enroll_tokens" edges to the EnrollToken entity.
func (_u *NodeUpdateOne) ClearEnrollTokens() *NodeUpdateOne {
	_u.mutation.ClearEnrollTokens()
	return _u
}

// RemoveEnrollTokenIDs removes the "enroll_tokens" edge to EnrollToken entities by IDs.
func (_u *NodeUpdateOne) RemoveEnrollTokenIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveEnrollTokenIDs(ids...)
	return _u
}

// RemoveEnrollTokens removes "enroll_tokens" edges to EnrollToken entities.
func (_u *NodeUpdateOne) RemoveEnrollTokens(v ...*EnrollToken) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollTokenIDs(ids...)
}

// ClearDirectors clears all "directors" edges to the Director entity.
func (_u *NodeUpdateOne) ClearDirectors() *NodeUpdateOne {
	_u.mutation.ClearDirectors()
	return _u
}

// RemoveDirectorIDs removes the "directors" edge to Director entities by IDs.
func (_u *NodeUpdateOne) RemoveDirectorIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveDirectorIDs(ids...)
	return _u
}

// RemoveDirectors removes "directors" edges to Director entities.
func (_u *NodeUpdateOne) RemoveDirectors(v ...*Director) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDirectorIDs(ids...)
}

// ClearCluster clears the "cluster" edge to the Cluster entity.
func (_u *NodeUpdateOne) ClearCluster() *NodeUpdateOne {
	_u.mutation.ClearCluster()
	return _u
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := node.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Node.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := node.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Node.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(node.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(node.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LvsWeight(); ok {
		_spec.SetField(node.FieldLvsWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLvsWeight(); ok {
		_spec.AddField(node.FieldLvsWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LvsEnabled(); ok {
		_spec.SetField(node.FieldLvsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastHeartbeatAt(); ok {
		_spec.SetField(node.FieldLastHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatAtCleared() {
		_spec.ClearField(node.FieldLastHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(node.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(node.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.CapabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCapabilitiesIDs(); len(nodes) > 0 && !_u.mutation.CapabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.CapabilitiesTable,
			Columns: []string{node.CapabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodecapability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigFilesIDs(); len(nodes) > 0 && !_u.mutation.ConfigFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ConfigFilesTable,
			Columns: []string{node.ConfigFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeconfigfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogTargetsIDs(); len(nodes) > 0 && !_u.mutation.LogTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.LogTargetsTable,
			Columns: []string{node.LogTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodelogtarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.SnapshotsTable,
			Columns: []string{node.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTasksIDs(); len(nodes) > 0 && !_u.mutation.DeployTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DeployTasksTable,
			Columns: []string{node.DeployTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RealServersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRealServersIDs(); len(nodes) > 0 && !_u.mutation.RealServersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealServersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.RealServersTable,
			Columns: []string{node.RealServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JoinTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJoinTokensIDs(); len(nodes) > 0 && !_u.mutation.JoinTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JoinTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.JoinTokensTable,
			Columns: []string{node.JoinTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jointoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollTokensIDs(); len(nodes) > 0 && !_u.mutation.EnrollTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.EnrollTokensTable,
			Columns: []string{node.EnrollTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrolltoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDirectorsIDs(); len(nodes) > 0 && !_u.mutation.DirectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.DirectorsTable,
			Columns: []string{node.DirectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(director.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClusterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ClusterTable,
			Columns: []string{node.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ClusterTable,
			Columns: []string{node.ClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
