// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/th/ngxcp/ent/cluster"
	"github.com/th/ngxcp/ent/node"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Role holds the value of the "role" field.
	Role node.Role `json:"role,omitempty"`
	// Status holds the value of the "status" field.
	Status node.Status `json:"status,omitempty"`
	// LvsWeight holds the value of the "lvs_weight" field.
	LvsWeight int `json:"lvs_weight,omitempty"`
	// LvsEnabled holds the value of the "lvs_enabled" field.
	LvsEnabled bool `json:"lvs_enabled,omitempty"`
	// LastHeartbeatAt holds the value of the "last_heartbeat_at" field.
	LastHeartbeatAt time.Time `json:"last_heartbeat_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges         NodeEdges `json:"edges"`
	cluster_nodes *int
	selectValues  sql.SelectValues
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// Capabilities holds the value of the capabilities edge.
	Capabilities []*NodeCapability `json:"capabilities,omitempty"`
	// ConfigFiles holds the value of the config_files edge.
	ConfigFiles []*NodeConfigFile `json:"config_files,omitempty"`
	// LogTargets holds the value of the log_targets edge.
	LogTargets []*NodeLogTarget `json:"log_targets,omitempty"`
	// Snapshots holds the value of the snapshots edge.
	Snapshots []*ConfigSnapshot `json:"snapshots,omitempty"`
	// DeployTasks holds the value of the deploy_tasks edge.
	DeployTasks []*DeployTask `json:"deploy_tasks,omitempty"`
	// RealServers holds the value of the real_servers edge.
	RealServers []*RealServer `json:"real_servers,omitempty"`
	// Cluster holds the value of the cluster edge.
	Cluster *Cluster `json:"cluster,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// CapabilitiesOrErr returns the Capabilities value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) CapabilitiesOrErr() ([]*NodeCapability, error) {
	if e.loadedTypes[0] {
		return e.Capabilities, nil
	}
	return nil, &NotLoadedError{edge: "capabilities"}
}

// ConfigFilesOrErr returns the ConfigFiles value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ConfigFilesOrErr() ([]*NodeConfigFile, error) {
	if e.loadedTypes[1] {
		return e.ConfigFiles, nil
	}
	return nil, &NotLoadedError{edge: "config_files"}
}

// LogTargetsOrErr returns the LogTargets value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) LogTargetsOrErr() ([]*NodeLogTarget, error) {
	if e.loadedTypes[2] {
		return e.LogTargets, nil
	}
	return nil, &NotLoadedError{edge: "log_targets"}
}

// SnapshotsOrErr returns the Snapshots value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) SnapshotsOrErr() ([]*ConfigSnapshot, error) {
	if e.loadedTypes[3] {
		return e.Snapshots, nil
	}
	return nil, &NotLoadedError{edge: "snapshots"}
}

// DeployTasksOrErr returns the DeployTasks value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) DeployTasksOrErr() ([]*DeployTask, error) {
	if e.loadedTypes[4] {
		return e.DeployTasks, nil
	}
	return nil, &NotLoadedError{edge: "deploy_tasks"}
}

// RealServersOrErr returns the RealServers value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) RealServersOrErr() ([]*RealServer, error) {
	if e.loadedTypes[5] {
		return e.RealServers, nil
	}
	return nil, &NotLoadedError{edge: "real_servers"}
}

// ClusterOrErr returns the Cluster value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) ClusterOrErr() (*Cluster, error) {
	if e.Cluster != nil {
		return e.Cluster, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: cluster.Label}
	}
	return nil, &NotLoadedError{edge: "cluster"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldLvsEnabled:
			values[i] = new(sql.NullBool)
		case node.FieldID, node.FieldLvsWeight:
			values[i] = new(sql.NullInt64)
		case node.FieldName, node.FieldAddress, node.FieldRole, node.FieldStatus:
			values[i] = new(sql.NullString)
		case node.FieldLastHeartbeatAt, node.FieldCreatedAt, node.FieldUpdatedAt, node.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case node.ForeignKeys[0]: // cluster_nodes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case node.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case node.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case node.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = node.Role(value.String)
			}
		case node.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = node.Status(value.String)
			}
		case node.FieldLvsWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lvs_weight", values[i])
			} else if value.Valid {
				_m.LvsWeight = int(value.Int64)
			}
		case node.FieldLvsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field lvs_enabled", values[i])
			} else if value.Valid {
				_m.LvsEnabled = value.Bool
			}
		case node.FieldLastHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat_at", values[i])
			} else if value.Valid {
				_m.LastHeartbeatAt = value.Time
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case node.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case node.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case node.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field cluster_nodes", value)
			} else if value.Valid {
				_m.cluster_nodes = new(int)
				*_m.cluster_nodes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCapabilities queries the "capabilities" edge of the Node entity.
func (_m *Node) QueryCapabilities() *NodeCapabilityQuery {
	return NewNodeClient(_m.config).QueryCapabilities(_m)
}

// QueryConfigFiles queries the "config_files" edge of the Node entity.
func (_m *Node) QueryConfigFiles() *NodeConfigFileQuery {
	return NewNodeClient(_m.config).QueryConfigFiles(_m)
}

// QueryLogTargets queries the "log_targets" edge of the Node entity.
func (_m *Node) QueryLogTargets() *NodeLogTargetQuery {
	return NewNodeClient(_m.config).QueryLogTargets(_m)
}

// QuerySnapshots queries the "snapshots" edge of the Node entity.
func (_m *Node) QuerySnapshots() *ConfigSnapshotQuery {
	return NewNodeClient(_m.config).QuerySnapshots(_m)
}

// QueryDeployTasks queries the "deploy_tasks" edge of the Node entity.
func (_m *Node) QueryDeployTasks() *DeployTaskQuery {
	return NewNodeClient(_m.config).QueryDeployTasks(_m)
}

// QueryRealServers queries the "real_servers" edge of the Node entity.
func (_m *Node) QueryRealServers() *RealServerQuery {
	return NewNodeClient(_m.config).QueryRealServers(_m)
}

// QueryCluster queries the "cluster" edge of the Node entity.
func (_m *Node) QueryCluster() *ClusterQuery {
	return NewNodeClient(_m.config).QueryCluster(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("lvs_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.LvsWeight))
	builder.WriteString(", ")
	builder.WriteString("lvs_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.LvsEnabled))
	builder.WriteString(", ")
	builder.WriteString("last_heartbeat_at=")
	builder.WriteString(_m.LastHeartbeatAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
