// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/cluster"
	"github.com/th/ngxcp/ent/configsnapshot"
	"github.com/th/ngxcp/ent/deploytask"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/nodecapability"
	"github.com/th/ngxcp/ent/nodeconfigfile"
	"github.com/th/ngxcp/ent/nodelogtarget"
	"github.com/th/ngxcp/ent/predicate"
	"github.com/th/ngxcp/ent/realserver"
)

// NodeQuery is the builder for querying Node entities.
type NodeQuery struct {
	config
	ctx              *QueryContext
	order            []node.OrderOption
	inters           []Interceptor
	predicates       []predicate.Node
	withCapabilities *NodeCapabilityQuery
	withConfigFiles  *NodeConfigFileQuery
	withLogTargets   *NodeLogTargetQuery
	withSnapshots    *ConfigSnapshotQuery
	withDeployTasks  *DeployTaskQuery
	withRealServers  *RealServerQuery
	withCluster      *ClusterQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NodeQuery builder.
func (_q *NodeQuery) Where(ps ...predicate.Node) *NodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NodeQuery) Limit(limit int) *NodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NodeQuery) Offset(offset int) *NodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NodeQuery) Unique(unique bool) *NodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NodeQuery) Order(o ...node.OrderOption) *NodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCapabilities chains the current query on the "capabilities" edge.
func (_q *NodeQuery) QueryCapabilities() *NodeCapabilityQuery {
	query := (&NodeCapabilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodecapability.Table, nodecapability.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.CapabilitiesTable, node.CapabilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConfigFiles chains the current query on the "config_files" edge.
func (_q *NodeQuery) QueryConfigFiles() *NodeConfigFileQuery {
	query := (&NodeConfigFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodeconfigfile.Table, nodeconfigfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.ConfigFilesTable, node.ConfigFilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLogTargets chains the current query on the "log_targets" edge.
func (_q *NodeQuery) QueryLogTargets() *NodeLogTargetQuery {
	query := (&NodeLogTargetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodelogtarget.Table, nodelogtarget.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.LogTargetsTable, node.LogTargetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySnapshots chains the current query on the "snapshots" edge.
func (_q *NodeQuery) QuerySnapshots() *ConfigSnapshotQuery {
	query := (&ConfigSnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(configsnapshot.Table, configsnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.SnapshotsTable, node.SnapshotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeployTasks chains the current query on the "deploy_tasks" edge.
func (_q *NodeQuery) QueryDeployTasks() *DeployTaskQuery {
	query := (&DeployTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(deploytask.Table, deploytask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.DeployTasksTable, node.DeployTasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRealServers chains the current query on the "real_servers" edge.
func (_q *NodeQuery) QueryRealServers() *RealServerQuery {
	query := (&RealServerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(realserver.Table, realserver.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.RealServersTable, node.RealServersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCluster chains the current query on the "cluster" edge.
func (_q *NodeQuery) QueryCluster() *ClusterQuery {
	query := (&ClusterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(cluster.Table, cluster.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, node.ClusterTable, node.ClusterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Node entity from the query.
// Returns a *NotFoundError when no Node was found.
func (_q *NodeQuery) First(ctx context.Context) (*Node, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{node.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NodeQuery) FirstX(ctx context.Context) *Node {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Node ID from the query.
// Returns a *NotFoundError when no Node ID was found.
func (_q *NodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{node.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NodeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Node entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Node entity is found.
// Returns a *NotFoundError when no Node entities are found.
func (_q *NodeQuery) Only(ctx context.Context) (*Node, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{node.Label}
	default:
		return nil, &NotSingularError{node.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NodeQuery) OnlyX(ctx context.Context) *Node {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Node ID in the query.
// Returns a *NotSingularError when more than one Node ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{node.Label}
	default:
		err = &NotSingularError{node.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Nodes.
func (_q *NodeQuery) All(ctx context.Context) ([]*Node, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Node, *NodeQuery]()
	return withInterceptors[[]*Node](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NodeQuery) AllX(ctx context.Context) []*Node {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Node IDs.
func (_q *NodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(node.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NodeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NodeQuery) Clone() *NodeQuery {
	if _q == nil {
		return nil
	}
	return &NodeQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]node.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Node{}, _q.predicates...),
		withCapabilities: _q.withCapabilities.Clone(),
		withConfigFiles:  _q.withConfigFiles.Clone(),
		withLogTargets:   _q.withLogTargets.Clone(),
		withSnapshots:    _q.withSnapshots.Clone(),
		withDeployTasks:  _q.withDeployTasks.Clone(),
		withRealServers:  _q.withRealServers.Clone(),
		withCluster:      _q.withCluster.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCapabilities tells the query-builder to eager-load the nodes that are connected to
// the "capabilities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithCapabilities(opts ...func(*NodeCapabilityQuery)) *NodeQuery {
	query := (&NodeCapabilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCapabilities = query
	return _q
}

// WithConfigFiles tells the query-builder to eager-load the nodes that are connected to
// the "config_files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithConfigFiles(opts ...func(*NodeConfigFileQuery)) *NodeQuery {
	query := (&NodeConfigFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConfigFiles = query
	return _q
}

// WithLogTargets tells the query-builder to eager-load the nodes that are connected to
// the "log_targets" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithLogTargets(opts ...func(*NodeLogTargetQuery)) *NodeQuery {
	query := (&NodeLogTargetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLogTargets = query
	return _q
}

// WithSnapshots tells the query-builder to eager-load the nodes that are connected to
// the "snapshots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithSnapshots(opts ...func(*ConfigSnapshotQuery)) *NodeQuery {
	query := (&ConfigSnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapshots = query
	return _q
}

// WithDeployTasks tells the query-builder to eager-load the nodes that are connected to
// the "deploy_tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithDeployTasks(opts ...func(*DeployTaskQuery)) *NodeQuery {
	query := (&DeployTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeployTasks = query
	return _q
}

// WithRealServers tells the query-builder to eager-load the nodes that are connected to
// the "real_servers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithRealServers(opts ...func(*RealServerQuery)) *NodeQuery {
	query := (&RealServerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRealServers = query
	return _q
}

// WithCluster tells the query-builder to eager-load the nodes that are connected to
// the "cluster" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithCluster(opts ...func(*ClusterQuery)) *NodeQuery {
	query := (&ClusterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCluster = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Node.Query().
//		GroupBy(node.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NodeQuery) GroupBy(field string, fields ...string) *NodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = node.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Node.Query().
//		Select(node.FieldName).
//		Scan(ctx, &v)
func (_q *NodeQuery) Select(fields ...string) *NodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NodeSelect{NodeQuery: _q}
	sbuild.label = node.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NodeSelect configured with the given aggregations.
func (_q *NodeQuery) Aggregate(fns ...AggregateFunc) *NodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !node.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Node, error) {
	var (
		nodes       = []*Node{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withCapabilities != nil,
			_q.withConfigFiles != nil,
			_q.withLogTargets != nil,
			_q.withSnapshots != nil,
			_q.withDeployTasks != nil,
			_q.withRealServers != nil,
			_q.withCluster != nil,
		}
	)
	if _q.withCluster != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, node.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Node).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Node{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCapabilities; query != nil {
		if err := _q.loadCapabilities(ctx, query, nodes,
			func(n *Node) { n.Edges.Capabilities = []*NodeCapability{} },
			func(n *Node, e *NodeCapability) { n.Edges.Capabilities = append(n.Edges.Capabilities, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withConfigFiles; query != nil {
		if err := _q.loadConfigFiles(ctx, query, nodes,
			func(n *Node) { n.Edges.ConfigFiles = []*NodeConfigFile{} },
			func(n *Node, e *NodeConfigFile) { n.Edges.ConfigFiles = append(n.Edges.ConfigFiles, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLogTargets; query != nil {
		if err := _q.loadLogTargets(ctx, query, nodes,
			func(n *Node) { n.Edges.LogTargets = []*NodeLogTarget{} },
			func(n *Node, e *NodeLogTarget) { n.Edges.LogTargets = append(n.Edges.LogTargets, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSnapshots; query != nil {
		if err := _q.loadSnapshots(ctx, query, nodes,
			func(n *Node) { n.Edges.Snapshots = []*ConfigSnapshot{} },
			func(n *Node, e *ConfigSnapshot) { n.Edges.Snapshots = append(n.Edges.Snapshots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDeployTasks; query != nil {
		if err := _q.loadDeployTasks(ctx, query, nodes,
			func(n *Node) { n.Edges.DeployTasks = []*DeployTask{} },
			func(n *Node, e *DeployTask) { n.Edges.DeployTasks = append(n.Edges.DeployTasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRealServers; query != nil {
		if err := _q.loadRealServers(ctx, query, nodes,
			func(n *Node) { n.Edges.RealServers = []*RealServer{} },
			func(n *Node, e *RealServer) { n.Edges.RealServers = append(n.Edges.RealServers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCluster; query != nil {
		if err := _q.loadCluster(ctx, query, nodes, nil,
			func(n *Node, e *Cluster) { n.Edges.Cluster = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NodeQuery) loadCapabilities(ctx context.Context, query *NodeCapabilityQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodeCapability)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.NodeCapability(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.CapabilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_capabilities
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_capabilities" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_capabilities" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadConfigFiles(ctx context.Context, query *NodeConfigFileQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodeConfigFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.NodeConfigFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.ConfigFilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_config_files
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_config_files" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_config_files" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadLogTargets(ctx context.Context, query *NodeLogTargetQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodeLogTarget)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.NodeLogTarget(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.LogTargetsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_log_targets
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_log_targets" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_log_targets" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadSnapshots(ctx context.Context, query *ConfigSnapshotQuery, nodes []*Node, init func(*Node), assign func(*Node, *ConfigSnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ConfigSnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.SnapshotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_snapshots
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_snapshots" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_snapshots" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadDeployTasks(ctx context.Context, query *DeployTaskQuery, nodes []*Node, init func(*Node), assign func(*Node, *DeployTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DeployTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.DeployTasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_deploy_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_deploy_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_deploy_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadRealServers(ctx context.Context, query *RealServerQuery, nodes []*Node, init func(*Node), assign func(*Node, *RealServer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RealServer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.RealServersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.node_real_servers
		if fk == nil {
			return fmt.Errorf(`foreign-key "node_real_servers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_real_servers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadCluster(ctx context.Context, query *ClusterQuery, nodes []*Node, init func(*Node), assign func(*Node, *Cluster)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Node)
	for i := range nodes {
		if nodes[i].cluster_nodes == nil {
			continue
		}
		fk := *nodes[i].cluster_nodes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cluster.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cluster_nodes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *NodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for i := range fields {
			if fields[i] != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(node.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = node.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NodeGroupBy is the group-by builder for Node entities.
type NodeGroupBy struct {
	selector
	build *NodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NodeGroupBy) Aggregate(fns ...AggregateFunc) *NodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeQuery, *NodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NodeGroupBy) sqlScan(ctx context.Context, root *NodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NodeSelect is the builder for selecting fields of Node entities.
type NodeSelect struct {
	*NodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NodeSelect) Aggregate(fns ...AggregateFunc) *NodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeQuery, *NodeSelect](ctx, _s.NodeQuery, _s, _s.inters, v)
}

func (_s *NodeSelect) sqlScan(ctx context.Context, root *NodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
