// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/node"
	"github.com/th/ngxcp/ent/realserver"
)

// RealServerCreate is the builder for creating a RealServer entity.
type RealServerCreate struct {
	config
	mutation *RealServerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVip sets the "vip" field.
func (_c *RealServerCreate) SetVip(v string) *RealServerCreate {
	_c.mutation.SetVip(v)
	return _c
}

// SetVport sets the "vport" field.
func (_c *RealServerCreate) SetVport(v int) *RealServerCreate {
	_c.mutation.SetVport(v)
	return _c
}

// SetRip sets the "rip" field.
func (_c *RealServerCreate) SetRip(v string) *RealServerCreate {
	_c.mutation.SetRip(v)
	return _c
}

// SetRport sets the "rport" field.
func (_c *RealServerCreate) SetRport(v int) *RealServerCreate {
	_c.mutation.SetRport(v)
	return _c
}

// SetWeight sets the "weight" field.
func (_c *RealServerCreate) SetWeight(v int) *RealServerCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableWeight(v *int) *RealServerCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RealServerCreate) SetEnabled(v bool) *RealServerCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableEnabled(v *bool) *RealServerCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *RealServerCreate) SetProtocol(v realserver.Protocol) *RealServerCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableProtocol(v *realserver.Protocol) *RealServerCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *RealServerCreate) SetState(v realserver.State) *RealServerCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableState(v *realserver.State) *RealServerCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RealServerCreate) SetCreatedAt(v time.Time) *RealServerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableCreatedAt(v *time.Time) *RealServerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RealServerCreate) SetUpdatedAt(v time.Time) *RealServerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableUpdatedAt(v *time.Time) *RealServerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RealServerCreate) SetDeletedAt(v time.Time) *RealServerCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RealServerCreate) SetNillableDeletedAt(v *time.Time) *RealServerCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetNodeID sets the "node" edge to the Node entity by ID.
func (_c *RealServerCreate) SetNodeID(id int) *RealServerCreate {
	_c.mutation.SetNodeID(id)
	return _c
}

// SetNillableNodeID sets the "node" edge to the Node entity by ID if the given value is not nil.
func (_c *RealServerCreate) SetNillableNodeID(id *int) *RealServerCreate {
	if id != nil {
		_c = _c.SetNodeID(*id)
	}
	return _c
}

// SetNode sets the "node" edge to the Node entity.
func (_c *RealServerCreate) SetNode(v *Node) *RealServerCreate {
	return _c.SetNodeID(v.ID)
}

// Mutation returns the RealServerMutation object of the builder.
func (_c *RealServerCreate) Mutation() *RealServerMutation {
	return _c.mutation
}

// Save creates the RealServer in the database.
func (_c *RealServerCreate) Save(ctx context.Context) (*RealServer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RealServerCreate) SaveX(ctx context.Context) *RealServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealServerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealServerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RealServerCreate) defaults() {
	if _, ok := _c.mutation.Weight(); !ok {
		v := realserver.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := realserver.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		v := realserver.DefaultProtocol
		_c.mutation.SetProtocol(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := realserver.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := realserver.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RealServerCreate) check() error {
	if _, ok := _c.mutation.Vip(); !ok {
		return &ValidationError{Name: "vip", err: errors.New(`ent: missing required field "RealServer.vip"`)}
	}
	if _, ok := _c.mutation.Vport(); !ok {
		return &ValidationError{Name: "vport", err: errors.New(`ent: missing required field "RealServer.vport"`)}
	}
	if _, ok := _c.mutation.Rip(); !ok {
		return &ValidationError{Name: "rip", err: errors.New(`ent: missing required field "RealServer.rip"`)}
	}
	if _, ok := _c.mutation.Rport(); !ok {
		return &ValidationError{Name: "rport", err: errors.New(`ent: missing required field "RealServer.rport"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "RealServer.weight"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RealServer.enabled"`)}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "RealServer.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := realserver.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "RealServer.protocol": %w`, err)}
		}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := realserver.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RealServer.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RealServer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RealServer.updated_at"`)}
	}
	return nil
}

func (_c *RealServerCreate) sqlSave(ctx context.Context) (*RealServer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RealServerCreate) createSpec() (*RealServer, *sqlgraph.CreateSpec) {
	var (
		_node = &RealServer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(realserver.Table, sqlgraph.NewFieldSpec(realserver.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Vip(); ok {
		_spec.SetField(realserver.FieldVip, field.TypeString, value)
		_node.Vip = value
	}
	if value, ok := _c.mutation.Vport(); ok {
		_spec.SetField(realserver.FieldVport, field.TypeInt, value)
		_node.Vport = value
	}
	if value, ok := _c.mutation.Rip(); ok {
		_spec.SetField(realserver.FieldRip, field.TypeString, value)
		_node.Rip = value
	}
	if value, ok := _c.mutation.Rport(); ok {
		_spec.SetField(realserver.FieldRport, field.TypeInt, value)
		_node.Rport = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(realserver.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(realserver.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(realserver.FieldProtocol, field.TypeEnum, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(realserver.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(realserver.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(realserver.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(realserver.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   realserver.NodeTable,
			Columns: []string{realserver.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.node_real_servers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealServer.Create().
//		SetVip(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealServerUpsert) {
//			SetVip(v+v).
//		}).
//		Exec(ctx)
func (_c *RealServerCreate) OnConflict(opts ...sql.ConflictOption) *RealServerUpsertOne {
	_c.conflict = opts
	return &RealServerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealServer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealServerCreate) OnConflictColumns(columns ...string) *RealServerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealServerUpsertOne{
		create: _c,
	}
}

type (
	// RealServerUpsertOne is the builder for "upsert"-ing
	//  one RealServer node.
	RealServerUpsertOne struct {
		create *RealServerCreate
	}

	// RealServerUpsert is the "OnConflict" setter.
	RealServerUpsert struct {
		*sql.UpdateSet
	}
)

// SetVip sets the "vip" field.
func (u *RealServerUpsert) SetVip(v string) *RealServerUpsert {
	u.Set(realserver.FieldVip, v)
	return u
}

// UpdateVip sets the "vip" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateVip() *RealServerUpsert {
	u.SetExcluded(realserver.FieldVip)
	return u
}

// SetVport sets the "vport" field.
func (u *RealServerUpsert) SetVport(v int) *RealServerUpsert {
	u.Set(realserver.FieldVport, v)
	return u
}

// UpdateVport sets the "vport" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateVport() *RealServerUpsert {
	u.SetExcluded(realserver.FieldVport)
	return u
}

// AddVport adds v to the "vport" field.
func (u *RealServerUpsert) AddVport(v int) *RealServerUpsert {
	u.Add(realserver.FieldVport, v)
	return u
}

// SetRip sets the "rip" field.
func (u *RealServerUpsert) SetRip(v string) *RealServerUpsert {
	u.Set(realserver.FieldRip, v)
	return u
}

// UpdateRip sets the "rip" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateRip() *RealServerUpsert {
	u.SetExcluded(realserver.FieldRip)
	return u
}

// SetRport sets the "rport" field.
func (u *RealServerUpsert) SetRport(v int) *RealServerUpsert {
	u.Set(realserver.FieldRport, v)
	return u
}

// UpdateRport sets the "rport" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateRport() *RealServerUpsert {
	u.SetExcluded(realserver.FieldRport)
	return u
}

// AddRport adds v to the "rport" field.
func (u *RealServerUpsert) AddRport(v int) *RealServerUpsert {
	u.Add(realserver.FieldRport, v)
	return u
}

// SetWeight sets the "weight" field.
func (u *RealServerUpsert) SetWeight(v int) *RealServerUpsert {
	u.Set(realserver.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateWeight() *RealServerUpsert {
	u.SetExcluded(realserver.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *RealServerUpsert) AddWeight(v int) *RealServerUpsert {
	u.Add(realserver.FieldWeight, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RealServerUpsert) SetEnabled(v bool) *RealServerUpsert {
	u.Set(realserver.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateEnabled() *RealServerUpsert {
	u.SetExcluded(realserver.FieldEnabled)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *RealServerUpsert) SetProtocol(v realserver.Protocol) *RealServerUpsert {
	u.Set(realserver.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateProtocol() *RealServerUpsert {
	u.SetExcluded(realserver.FieldProtocol)
	return u
}

// SetState sets the "state" field.
func (u *RealServerUpsert) SetState(v realserver.State) *RealServerUpsert {
	u.Set(realserver.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateState() *RealServerUpsert {
	u.SetExcluded(realserver.FieldState)
	return u
}

// ClearState clears the value of the "state" field.
func (u *RealServerUpsert) ClearState() *RealServerUpsert {
	u.SetNull(realserver.FieldState)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealServerUpsert) SetUpdatedAt(v time.Time) *RealServerUpsert {
	u.Set(realserver.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateUpdatedAt() *RealServerUpsert {
	u.SetExcluded(realserver.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealServerUpsert) SetDeletedAt(v time.Time) *RealServerUpsert {
	u.Set(realserver.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealServerUpsert) UpdateDeletedAt() *RealServerUpsert {
	u.SetExcluded(realserver.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealServerUpsert) ClearDeletedAt() *RealServerUpsert {
	u.SetNull(realserver.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RealServer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealServerUpsertOne) UpdateNewValues() *RealServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(realserver.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealServer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RealServerUpsertOne) Ignore() *RealServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealServerUpsertOne) DoNothing() *RealServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealServerCreate.OnConflict
// documentation for more info.
func (u *RealServerUpsertOne) Update(set func(*RealServerUpsert)) *RealServerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealServerUpsert{UpdateSet: update})
	}))
	return u
}

// SetVip sets the "vip" field.
func (u *RealServerUpsertOne) SetVip(v string) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetVip(v)
	})
}

// UpdateVip sets the "vip" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateVip() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateVip()
	})
}

// SetVport sets the "vport" field.
func (u *RealServerUpsertOne) SetVport(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetVport(v)
	})
}

// AddVport adds v to the "vport" field.
func (u *RealServerUpsertOne) AddVport(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.AddVport(v)
	})
}

// UpdateVport sets the "vport" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateVport() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateVport()
	})
}

// SetRip sets the "rip" field.
func (u *RealServerUpsertOne) SetRip(v string) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetRip(v)
	})
}

// UpdateRip sets the "rip" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateRip() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateRip()
	})
}

// SetRport sets the "rport" field.
func (u *RealServerUpsertOne) SetRport(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetRport(v)
	})
}

// AddRport adds v to the "rport" field.
func (u *RealServerUpsertOne) AddRport(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.AddRport(v)
	})
}

// UpdateRport sets the "rport" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateRport() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateRport()
	})
}

// SetWeight sets the "weight" field.
func (u *RealServerUpsertOne) SetWeight(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *RealServerUpsertOne) AddWeight(v int) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateWeight() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RealServerUpsertOne) SetEnabled(v bool) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateEnabled() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateEnabled()
	})
}

// SetProtocol sets the "protocol" field.
func (u *RealServerUpsertOne) SetProtocol(v realserver.Protocol) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateProtocol() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateProtocol()
	})
}

// SetState sets the "state" field.
func (u *RealServerUpsertOne) SetState(v realserver.State) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateState() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *RealServerUpsertOne) ClearState() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.ClearState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealServerUpsertOne) SetUpdatedAt(v time.Time) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateUpdatedAt() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealServerUpsertOne) SetDeletedAt(v time.Time) *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealServerUpsertOne) UpdateDeletedAt() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealServerUpsertOne) ClearDeletedAt() *RealServerUpsertOne {
	return u.Update(func(s *RealServerUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *RealServerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealServerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealServerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RealServerUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RealServerUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RealServerCreateBulk is the builder for creating many RealServer entities in bulk.
type RealServerCreateBulk struct {
	config
	err      error
	builders []*RealServerCreate
	conflict []sql.ConflictOption
}

// Save creates the RealServer entities in the database.
func (_c *RealServerCreateBulk) Save(ctx context.Context) ([]*RealServer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RealServer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RealServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RealServerCreateBulk) SaveX(ctx context.Context) []*RealServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealServerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealServerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealServer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealServerUpsert) {
//			SetVip(v+v).
//		}).
//		Exec(ctx)
func (_c *RealServerCreateBulk) OnConflict(opts ...sql.ConflictOption) *RealServerUpsertBulk {
	_c.conflict = opts
	return &RealServerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealServer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealServerCreateBulk) OnConflictColumns(columns ...string) *RealServerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealServerUpsertBulk{
		create: _c,
	}
}

// RealServerUpsertBulk is the builder for "upsert"-ing
// a bulk of RealServer nodes.
type RealServerUpsertBulk struct {
	create *RealServerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RealServer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealServerUpsertBulk) UpdateNewValues() *RealServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(realserver.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealServer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RealServerUpsertBulk) Ignore() *RealServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealServerUpsertBulk) DoNothing() *RealServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealServerCreateBulk.OnConflict
// documentation for more info.
func (u *RealServerUpsertBulk) Update(set func(*RealServerUpsert)) *RealServerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealServerUpsert{UpdateSet: update})
	}))
	return u
}

// SetVip sets the "vip" field.
func (u *RealServerUpsertBulk) SetVip(v string) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetVip(v)
	})
}

// UpdateVip sets the "vip" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateVip() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateVip()
	})
}

// SetVport sets the "vport" field.
func (u *RealServerUpsertBulk) SetVport(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetVport(v)
	})
}

// AddVport adds v to the "vport" field.
func (u *RealServerUpsertBulk) AddVport(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.AddVport(v)
	})
}

// UpdateVport sets the "vport" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateVport() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateVport()
	})
}

// SetRip sets the "rip" field.
func (u *RealServerUpsertBulk) SetRip(v string) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetRip(v)
	})
}

// UpdateRip sets the "rip" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateRip() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateRip()
	})
}

// SetRport sets the "rport" field.
func (u *RealServerUpsertBulk) SetRport(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetRport(v)
	})
}

// AddRport adds v to the "rport" field.
func (u *RealServerUpsertBulk) AddRport(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.AddRport(v)
	})
}

// UpdateRport sets the "rport" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateRport() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateRport()
	})
}

// SetWeight sets the "weight" field.
func (u *RealServerUpsertBulk) SetWeight(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *RealServerUpsertBulk) AddWeight(v int) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateWeight() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RealServerUpsertBulk) SetEnabled(v bool) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateEnabled() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateEnabled()
	})
}

// SetProtocol sets the "protocol" field.
func (u *RealServerUpsertBulk) SetProtocol(v realserver.Protocol) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateProtocol() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateProtocol()
	})
}

// SetState sets the "state" field.
func (u *RealServerUpsertBulk) SetState(v realserver.State) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateState() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *RealServerUpsertBulk) ClearState() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.ClearState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealServerUpsertBulk) SetUpdatedAt(v time.Time) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateUpdatedAt() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealServerUpsertBulk) SetDeletedAt(v time.Time) *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealServerUpsertBulk) UpdateDeletedAt() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealServerUpsertBulk) ClearDeletedAt() *RealServerUpsertBulk {
	return u.Update(func(s *RealServerUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *RealServerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RealServerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealServerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealServerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
