// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/th/ngxcp/ent/securityevent"
)

// SecurityEventCreate is the builder for creating a SecurityEvent entity.
type SecurityEventCreate struct {
	config
	mutation *SecurityEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRuleID sets the "rule_id" field.
func (_c *SecurityEventCreate) SetRuleID(v string) *SecurityEventCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetRuleName sets the "rule_name" field.
func (_c *SecurityEventCreate) SetRuleName(v string) *SecurityEventCreate {
	_c.mutation.SetRuleName(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *SecurityEventCreate) SetLevel(v securityevent.Level) *SecurityEventCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNode sets the "node" field.
func (_c *SecurityEventCreate) SetNode(v string) *SecurityEventCreate {
	_c.mutation.SetNode(v)
	return _c
}

// SetNillableNode sets the "node" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableNode(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetNode(*v)
	}
	return _c
}

// SetSample sets the "sample" field.
func (_c *SecurityEventCreate) SetSample(v string) *SecurityEventCreate {
	_c.mutation.SetSample(v)
	return _c
}

// SetNillableSample sets the "sample" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableSample(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetSample(*v)
	}
	return _c
}

// SetHandled sets the "handled" field.
func (_c *SecurityEventCreate) SetHandled(v bool) *SecurityEventCreate {
	_c.mutation.SetHandled(v)
	return _c
}

// SetNillableHandled sets the "handled" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableHandled(v *bool) *SecurityEventCreate {
	if v != nil {
		_c.SetHandled(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *SecurityEventCreate) SetAction(v securityevent.Action) *SecurityEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableAction(v *securityevent.Action) *SecurityEventCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SecurityEventCreate) SetCreatedAt(v time.Time) *SecurityEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableCreatedAt(v *time.Time) *SecurityEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SecurityEventMutation object of the builder.
func (_c *SecurityEventCreate) Mutation() *SecurityEventMutation {
	return _c.mutation
}

// Save creates the SecurityEvent in the database.
func (_c *SecurityEventCreate) Save(ctx context.Context) (*SecurityEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecurityEventCreate) SaveX(ctx context.Context) *SecurityEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecurityEventCreate) defaults() {
	if _, ok := _c.mutation.Handled(); !ok {
		v := securityevent.DefaultHandled
		_c.mutation.SetHandled(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := securityevent.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := securityevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecurityEventCreate) check() error {
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "SecurityEvent.rule_id"`)}
	}
	if _, ok := _c.mutation.RuleName(); !ok {
		return &ValidationError{Name: "rule_name", err: errors.New(`ent: missing required field "SecurityEvent.rule_name"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "SecurityEvent.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := securityevent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Handled(); !ok {
		return &ValidationError{Name: "handled", err: errors.New(`ent: missing required field "SecurityEvent.handled"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SecurityEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := securityevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SecurityEvent.created_at"`)}
	}
	return nil
}

func (_c *SecurityEventCreate) sqlSave(ctx context.Context) (*SecurityEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecurityEventCreate) createSpec() (*SecurityEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SecurityEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(securityevent.Table, sqlgraph.NewFieldSpec(securityevent.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(securityevent.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.RuleName(); ok {
		_spec.SetField(securityevent.FieldRuleName, field.TypeString, value)
		_node.RuleName = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(securityevent.FieldLevel, field.TypeEnum, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Node(); ok {
		_spec.SetField(securityevent.FieldNode, field.TypeString, value)
		_node.Node = value
	}
	if value, ok := _c.mutation.Sample(); ok {
		_spec.SetField(securityevent.FieldSample, field.TypeString, value)
		_node.Sample = value
	}
	if value, ok := _c.mutation.Handled(); ok {
		_spec.SetField(securityevent.FieldHandled, field.TypeBool, value)
		_node.Handled = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(securityevent.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(securityevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityEvent.Create().
//		SetRuleID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityEventUpsert) {
//			SetRuleID(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityEventCreate) OnConflict(opts ...sql.ConflictOption) *SecurityEventUpsertOne {
	_c.conflict = opts
	return &SecurityEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityEventCreate) OnConflictColumns(columns ...string) *SecurityEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityEventUpsertOne{
		create: _c,
	}
}

type (
	// SecurityEventUpsertOne is the builder for "upsert"-ing
	//  one SecurityEvent node.
	SecurityEventUpsertOne struct {
		create *SecurityEventCreate
	}

	// SecurityEventUpsert is the "OnConflict" setter.
	SecurityEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetRuleID sets the "rule_id" field.
func (u *SecurityEventUpsert) SetRuleID(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldRuleID, v)
	return u
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateRuleID() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldRuleID)
	return u
}

// SetRuleName sets the "rule_name" field.
func (u *SecurityEventUpsert) SetRuleName(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldRuleName, v)
	return u
}

// UpdateRuleName sets the "rule_name" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateRuleName() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldRuleName)
	return u
}

// SetLevel sets the "level" field.
func (u *SecurityEventUpsert) SetLevel(v securityevent.Level) *SecurityEventUpsert {
	u.Set(securityevent.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateLevel() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldLevel)
	return u
}

// SetNode sets the "node" field.
func (u *SecurityEventUpsert) SetNode(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldNode, v)
	return u
}

// UpdateNode sets the "node" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateNode() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldNode)
	return u
}

// ClearNode clears the value of the "node" field.
func (u *SecurityEventUpsert) ClearNode() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldNode)
	return u
}

// SetSample sets the "sample" field.
func (u *SecurityEventUpsert) SetSample(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldSample, v)
	return u
}

// UpdateSample sets the "sample" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateSample() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldSample)
	return u
}

// ClearSample clears the value of the "sample" field.
func (u *SecurityEventUpsert) ClearSample() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldSample)
	return u
}

// SetHandled sets the "handled" field.
func (u *SecurityEventUpsert) SetHandled(v bool) *SecurityEventUpsert {
	u.Set(securityevent.FieldHandled, v)
	return u
}

// UpdateHandled sets the "handled" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateHandled() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldHandled)
	return u
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsert) SetAction(v securityevent.Action) *SecurityEventUpsert {
	u.Set(securityevent.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateAction() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldAction)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityEventUpsertOne) UpdateNewValues() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(securityevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecurityEventUpsertOne) Ignore() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityEventUpsertOne) DoNothing() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityEventCreate.OnConflict
// documentation for more info.
func (u *SecurityEventUpsertOne) Update(set func(*SecurityEventUpsert)) *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuleID sets the "rule_id" field.
func (u *SecurityEventUpsertOne) SetRuleID(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRuleID(v)
	})
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateRuleID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRuleID()
	})
}

// SetRuleName sets the "rule_name" field.
func (u *SecurityEventUpsertOne) SetRuleName(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRuleName(v)
	})
}

// UpdateRuleName sets the "rule_name" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateRuleName() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRuleName()
	})
}

// SetLevel sets the "level" field.
func (u *SecurityEventUpsertOne) SetLevel(v securityevent.Level) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateLevel() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateLevel()
	})
}

// SetNode sets the "node" field.
func (u *SecurityEventUpsertOne) SetNode(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetNode(v)
	})
}

// UpdateNode sets the "node" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateNode() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateNode()
	})
}

// ClearNode clears the value of the "node" field.
func (u *SecurityEventUpsertOne) ClearNode() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearNode()
	})
}

// SetSample sets the "sample" field.
func (u *SecurityEventUpsertOne) SetSample(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSample(v)
	})
}

// UpdateSample sets the "sample" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateSample() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSample()
	})
}

// ClearSample clears the value of the "sample" field.
func (u *SecurityEventUpsertOne) ClearSample() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearSample()
	})
}

// SetHandled sets the "handled" field.
func (u *SecurityEventUpsertOne) SetHandled(v bool) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetHandled(v)
	})
}

// UpdateHandled sets the "handled" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateHandled() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateHandled()
	})
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsertOne) SetAction(v securityevent.Action) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateAction() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAction()
	})
}

// Exec executes the query.
func (u *SecurityEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecurityEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecurityEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecurityEventCreateBulk is the builder for creating many SecurityEvent entities in bulk.
type SecurityEventCreateBulk struct {
	config
	err      error
	builders []*SecurityEventCreate
	conflict []sql.ConflictOption
}

// Save creates the SecurityEvent entities in the database.
func (_c *SecurityEventCreateBulk) Save(ctx context.Context) ([]*SecurityEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecurityEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecurityEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecurityEventCreateBulk) SaveX(ctx context.Context) []*SecurityEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityEventUpsert) {
//			SetRuleID(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecurityEventUpsertBulk {
	_c.conflict = opts
	return &SecurityEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityEventCreateBulk) OnConflictColumns(columns ...string) *SecurityEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityEventUpsertBulk{
		create: _c,
	}
}

// SecurityEventUpsertBulk is the builder for "upsert"-ing
// a bulk of SecurityEvent nodes.
type SecurityEventUpsertBulk struct {
	create *SecurityEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityEventUpsertBulk) UpdateNewValues() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(securityevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecurityEventUpsertBulk) Ignore() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityEventUpsertBulk) DoNothing() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityEventCreateBulk.OnConflict
// documentation for more info.
func (u *SecurityEventUpsertBulk) Update(set func(*SecurityEventUpsert)) *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuleID sets the "rule_id" field.
func (u *SecurityEventUpsertBulk) SetRuleID(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRuleID(v)
	})
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateRuleID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRuleID()
	})
}

// SetRuleName sets the "rule_name" field.
func (u *SecurityEventUpsertBulk) SetRuleName(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRuleName(v)
	})
}

// UpdateRuleName sets the "rule_name" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateRuleName() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRuleName()
	})
}

// SetLevel sets the "level" field.
func (u *SecurityEventUpsertBulk) SetLevel(v securityevent.Level) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateLevel() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateLevel()
	})
}

// SetNode sets the "node" field.
func (u *SecurityEventUpsertBulk) SetNode(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetNode(v)
	})
}

// UpdateNode sets the "node" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateNode() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateNode()
	})
}

// ClearNode clears the value of the "node" field.
func (u *SecurityEventUpsertBulk) ClearNode() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearNode()
	})
}

// SetSample sets the "sample" field.
func (u *SecurityEventUpsertBulk) SetSample(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSample(v)
	})
}

// UpdateSample sets the "sample" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateSample() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSample()
	})
}

// ClearSample clears the value of the "sample" field.
func (u *SecurityEventUpsertBulk) ClearSample() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearSample()
	})
}

// SetHandled sets the "handled" field.
func (u *SecurityEventUpsertBulk) SetHandled(v bool) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetHandled(v)
	})
}

// UpdateHandled sets the "handled" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateHandled() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateHandled()
	})
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsertBulk) SetAction(v securityevent.Action) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateAction() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAction()
	})
}

// Exec executes the query.
func (u *SecurityEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecurityEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
