// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/th/ngxcp/ent/director"
	"github.com/th/ngxcp/ent/virtualservice"
)

// VirtualService is the model entity for the VirtualService schema.
type VirtualService struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 虚拟服务地址，如 192.168.5.5
	Vip string `json:"vip,omitempty"`
	// 虚拟服务端口（DR 模式下必须等于 RS 端口）
	Port int `json:"port,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol virtualservice.Protocol `json:"protocol,omitempty"`
	// 调度算法：rr 轮询 / wrr 加权轮询 / lc 最少连接 / wlc 加权最少连接
	Scheduler virtualservice.Scheduler `json:"scheduler,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VirtualServiceQuery when eager-loading is set.
	Edges                     VirtualServiceEdges `json:"edges"`
	director_virtual_services *int
	selectValues              sql.SelectValues
}

// VirtualServiceEdges holds the relations/edges for other nodes in the graph.
type VirtualServiceEdges struct {
	// Director holds the value of the director edge.
	Director *Director `json:"director,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DirectorOrErr returns the Director value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VirtualServiceEdges) DirectorOrErr() (*Director, error) {
	if e.Director != nil {
		return e.Director, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: director.Label}
	}
	return nil, &NotLoadedError{edge: "director"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VirtualService) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case virtualservice.FieldEnabled:
			values[i] = new(sql.NullBool)
		case virtualservice.FieldID, virtualservice.FieldPort:
			values[i] = new(sql.NullInt64)
		case virtualservice.FieldVip, virtualservice.FieldProtocol, virtualservice.FieldScheduler:
			values[i] = new(sql.NullString)
		case virtualservice.FieldCreatedAt, virtualservice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case virtualservice.ForeignKeys[0]: // director_virtual_services
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VirtualService fields.
func (_m *VirtualService) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case virtualservice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case virtualservice.FieldVip:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vip", values[i])
			} else if value.Valid {
				_m.Vip = value.String
			}
		case virtualservice.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case virtualservice.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = virtualservice.Protocol(value.String)
			}
		case virtualservice.FieldScheduler:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scheduler", values[i])
			} else if value.Valid {
				_m.Scheduler = virtualservice.Scheduler(value.String)
			}
		case virtualservice.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case virtualservice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case virtualservice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case virtualservice.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field director_virtual_services", value)
			} else if value.Valid {
				_m.director_virtual_services = new(int)
				*_m.director_virtual_services = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VirtualService.
// This includes values selected through modifiers, order, etc.
func (_m *VirtualService) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDirector queries the "director" edge of the VirtualService entity.
func (_m *VirtualService) QueryDirector() *DirectorQuery {
	return NewVirtualServiceClient(_m.config).QueryDirector(_m)
}

// Update returns a builder for updating this VirtualService.
// Note that you need to call VirtualService.Unwrap() before calling this method if this VirtualService
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VirtualService) Update() *VirtualServiceUpdateOne {
	return NewVirtualServiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VirtualService entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VirtualService) Unwrap() *VirtualService {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VirtualService is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VirtualService) String() string {
	var builder strings.Builder
	builder.WriteString("VirtualService(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("vip=")
	builder.WriteString(_m.Vip)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	builder.WriteString("scheduler=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scheduler))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VirtualServices is a parsable slice of VirtualService.
type VirtualServices []*VirtualService
