// Code generated by ent, DO NOT EDIT.

package nodecapability

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodecapability type in the database.
	Label = "node_capability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldKernel holds the string denoting the kernel field in the database.
	FieldKernel = "kernel"
	// FieldHasKeepalived holds the string denoting the has_keepalived field in the database.
	FieldHasKeepalived = "has_keepalived"
	// FieldHasIpvsadm holds the string denoting the has_ipvsadm field in the database.
	FieldHasIpvsadm = "has_ipvsadm"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldPrefix holds the string denoting the prefix field in the database.
	FieldPrefix = "prefix"
	// FieldConfPath holds the string denoting the conf_path field in the database.
	FieldConfPath = "conf_path"
	// FieldSbinPath holds the string denoting the sbin_path field in the database.
	FieldSbinPath = "sbin_path"
	// FieldModules holds the string denoting the modules field in the database.
	FieldModules = "modules"
	// FieldRawArgs holds the string denoting the raw_args field in the database.
	FieldRawArgs = "raw_args"
	// FieldConfigHash holds the string denoting the config_hash field in the database.
	FieldConfigHash = "config_hash"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldSystemInfo holds the string denoting the system_info field in the database.
	FieldSystemInfo = "system_info"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// Table holds the table name of the nodecapability in the database.
	Table = "node_capabilities"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "node_capabilities"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_capabilities"
)

// Columns holds all SQL columns for nodecapability fields.
var Columns = []string{
	FieldID,
	FieldHostname,
	FieldOs,
	FieldKernel,
	FieldHasKeepalived,
	FieldHasIpvsadm,
	FieldVersion,
	FieldPrefix,
	FieldConfPath,
	FieldSbinPath,
	FieldModules,
	FieldRawArgs,
	FieldConfigHash,
	FieldChecksum,
	FieldSystemInfo,
	FieldCapturedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "node_capabilities"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"node_capabilities",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHasKeepalived holds the default value on creation for the "has_keepalived" field.
	DefaultHasKeepalived bool
	// DefaultHasIpvsadm holds the default value on creation for the "has_ipvsadm" field.
	DefaultHasIpvsadm bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NodeCapability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByKernel orders the results by the kernel field.
func ByKernel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKernel, opts...).ToFunc()
}

// ByHasKeepalived orders the results by the has_keepalived field.
func ByHasKeepalived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasKeepalived, opts...).ToFunc()
}

// ByHasIpvsadm orders the results by the has_ipvsadm field.
func ByHasIpvsadm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasIpvsadm, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByPrefix orders the results by the prefix field.
func ByPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefix, opts...).ToFunc()
}

// ByConfPath orders the results by the conf_path field.
func ByConfPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfPath, opts...).ToFunc()
}

// BySbinPath orders the results by the sbin_path field.
func BySbinPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSbinPath, opts...).ToFunc()
}

// ByRawArgs orders the results by the raw_args field.
func ByRawArgs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawArgs, opts...).ToFunc()
}

// ByConfigHash orders the results by the config_hash field.
func ByConfigHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigHash, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// BySystemInfo orders the results by the system_info field.
func BySystemInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemInfo, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
	)
}
