// Code generated by ent, DO NOT EDIT.

package deploytask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/th/ngxcp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldID, id))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldAttempts, v))
}

// ErrorDetail applies equality check predicate on the "error_detail" field. It's identical to ErrorDetailEQ.
func ErrorDetail(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldErrorDetail, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldDeletedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldState, vs...))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v Phase) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v Phase) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...Phase) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...Phase) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldPhase, vs...))
}

// PhaseIsNil applies the IsNil predicate on the "phase" field.
func PhaseIsNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIsNull(FieldPhase))
}

// PhaseNotNil applies the NotNil predicate on the "phase" field.
func PhaseNotNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotNull(FieldPhase))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldAttempts, v))
}

// ErrorDetailEQ applies the EQ predicate on the "error_detail" field.
func ErrorDetailEQ(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldErrorDetail, v))
}

// ErrorDetailNEQ applies the NEQ predicate on the "error_detail" field.
func ErrorDetailNEQ(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldErrorDetail, v))
}

// ErrorDetailIn applies the In predicate on the "error_detail" field.
func ErrorDetailIn(vs ...string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldErrorDetail, vs...))
}

// ErrorDetailNotIn applies the NotIn predicate on the "error_detail" field.
func ErrorDetailNotIn(vs ...string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldErrorDetail, vs...))
}

// ErrorDetailGT applies the GT predicate on the "error_detail" field.
func ErrorDetailGT(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldErrorDetail, v))
}

// ErrorDetailGTE applies the GTE predicate on the "error_detail" field.
func ErrorDetailGTE(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldErrorDetail, v))
}

// ErrorDetailLT applies the LT predicate on the "error_detail" field.
func ErrorDetailLT(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldErrorDetail, v))
}

// ErrorDetailLTE applies the LTE predicate on the "error_detail" field.
func ErrorDetailLTE(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldErrorDetail, v))
}

// ErrorDetailContains applies the Contains predicate on the "error_detail" field.
func ErrorDetailContains(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldContains(FieldErrorDetail, v))
}

// ErrorDetailHasPrefix applies the HasPrefix predicate on the "error_detail" field.
func ErrorDetailHasPrefix(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldHasPrefix(FieldErrorDetail, v))
}

// ErrorDetailHasSuffix applies the HasSuffix predicate on the "error_detail" field.
func ErrorDetailHasSuffix(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldHasSuffix(FieldErrorDetail, v))
}

// ErrorDetailIsNil applies the IsNil predicate on the "error_detail" field.
func ErrorDetailIsNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIsNull(FieldErrorDetail))
}

// ErrorDetailNotNil applies the NotNil predicate on the "error_detail" field.
func ErrorDetailNotNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotNull(FieldErrorDetail))
}

// ErrorDetailEqualFold applies the EqualFold predicate on the "error_detail" field.
func ErrorDetailEqualFold(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEqualFold(FieldErrorDetail, v))
}

// ErrorDetailContainsFold applies the ContainsFold predicate on the "error_detail" field.
func ErrorDetailContainsFold(v string) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldContainsFold(FieldErrorDetail, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DeployTask {
	return predicate.DeployTask(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DeployTask {
	return predicate.DeployTask(sql.FieldNotNull(FieldDeletedAt))
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.DeployTask {
	return predicate.DeployTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.DeployTask {
	return predicate.DeployTask(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChangeOrder applies the HasEdge predicate on the "change_order" edge.
func HasChangeOrder() predicate.DeployTask {
	return predicate.DeployTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChangeOrderTable, ChangeOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChangeOrderWith applies the HasEdge predicate on the "change_order" edge with a given conditions (other predicates).
func HasChangeOrderWith(preds ...predicate.ChangeOrder) predicate.DeployTask {
	return predicate.DeployTask(func(s *sql.Selector) {
		step := newChangeOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeployTask) predicate.DeployTask {
	return predicate.DeployTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeployTask) predicate.DeployTask {
	return predicate.DeployTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeployTask) predicate.DeployTask {
	return predicate.DeployTask(sql.NotPredicates(p))
}
